const fs = require('fs');
const path = require('path');

const KNOWLEDGE_DIR = path.join(__dirname, 'data', 'knowledge');
const EXAMPLES_DIR = path.join(__dirname, 'data', 'examples');

function shuffleArray(arr) {
    const a = [...arr];
    for (let i = a.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
}

function generateExamples(knowledgeList, grade, subject, semester) {
    const semCode = semester === 'upper' ? 'u' : 'l';
    const allExamples = [];

    knowledgeList.forEach((k, idx) => {
        const kid = `${grade}_${subject}_${semCode}${String(idx + 1).padStart(3, '0')}`;
        const examples = [];
        const name = k.name;
        const formula = k.formula || '';
        const chapter = k.chapter || '';

        function addChoice(question, correctOption, wrongOptions, explanation) {
            const options = shuffleArray([correctOption, ...wrongOptions]);
            const labels = ['A', 'B', 'C', 'D'];
            let correctLabel = '';
            const optionStr = options.map((opt, i) => {
                if (opt === correctOption) correctLabel = labels[i];
                return `${labels[i]}. ${opt}`;
            }).join('  ');
            return {
                question: `选择题：${question} ${optionStr}`,
                answer: `答案：${correctLabel}. ${correctOption}。解析：${explanation}`
            };
        }

        const q1 = addChoice(
            `关于"${name}"的说法，下列哪一项是正确的？`,
            `这是${name}的正确描述`,
            ['完全错误的说法', '与该知识点无关的内容', '混淆概念的说法'],
            `本题考查对"${name}"概念的理解。学习英语语法和词汇时，要准确掌握其定义和用法。`
        );
        examples.push({ id: `${kid}_ex01`, knowledge_id: kid, question: q1.question, answer: q1.answer });

        const q2 = addChoice(
            `${name}的核心用法/形式是？`,
            formula || `${name}的核心内容`,
            ['错误的形式', '不相关的结构', '另一个语法点的用法'],
            `${name}的核心是：${formula || '详见知识点内容'}。掌握核心用法是学好该知识点的关键。`
        );
        examples.push({ id: `${kid}_ex02`, knowledge_id: kid, question: q2.question, answer: q2.answer });

        examples.push({
            id: `${kid}_ex03`,
            knowledge_id: kid,
            question: `填空题：${name}的主要结构/形式是 ______。`,
            answer: `答案：${formula || '详见知识点内容'}。解析：这是${name}的重要内容，需要在理解的基础上熟练掌握。\n学习要点：\n1. 理解基本概念\n2. 掌握常见用法\n3. 通过例句加深理解\n4. 多做练习巩固`
        });

        examples.push({
            id: `${kid}_ex04`,
            knowledge_id: kid,
            question: `判断题：学习${name}只需要背规则，不需要实际运用。（  ）`,
            answer: `答案：错误。解析：学习${name}不仅要掌握规则，更要在实际语境中运用。语言学习重在实践，要通过听说读写多方面练习来掌握。`
        });

        const q5 = addChoice(
            `学习${name}时，最好的方法是？`,
            '理解规则 + 例句学习 + 实际运用',
            ['只背语法规则', '只做题不总结', '考前临时抱佛脚'],
            '学习英语语法和词汇的最佳方法是：先理解规则，再通过例句学习，最后在实际运用中掌握。'
        );
        examples.push({ id: `${kid}_ex05`, knowledge_id: kid, question: q5.question, answer: q5.answer });

        examples.push({
            id: `${kid}_ex06`,
            knowledge_id: kid,
            question: `填空题：${name}属于 ______ 部分的内容。`,
            answer: `答案：${chapter}。解析：${name}是${chapter}中的重要知识点，掌握它对英语学习有重要意义。`
        });

        examples.push({
            id: `${kid}_ex07`,
            knowledge_id: kid,
            question: `判断题：${name}和其他英语知识没有联系。（  ）`,
            answer: `答案：错误。解析：英语知识是相互联系的。${name}与前后学过的词汇、语法都有密切联系，学习时要注意融会贯通，形成知识网络。`
        });

        const q8 = addChoice(
            `下列关于${name}的应用，正确的是？`,
            '可以在多种语境中正确使用',
            ['只能在一种情况下用', '完全没有实用价值', '只在考试中有用'],
            `${name}是重要的英语知识点，可以在多种语境中运用。学习时要注重实际应用能力的培养。`
        );
        examples.push({ id: `${kid}_ex08`, knowledge_id: kid, question: q8.question, answer: q8.answer });

        examples.push({
            id: `${kid}_ex09`,
            knowledge_id: kid,
            question: `简答题：请简述${name}的主要内容和用法。`,
            answer: `答案：${name}的主要内容包括：${formula || '详见知识点内容'}。\n要点总结：\n1. 基本概念和定义\n2. 核心用法和结构\n3. 常见例句和应用场景\n4. 注意事项和易错点\n\n这是英语学习的重要知识点，需要在理解的基础上多加练习和运用。`
        });

        const q10 = addChoice(
            `要掌握好${name}，最重要的是？`,
            '多练习、多运用、在语境中学习',
            ['只需要死记硬背', '只看语法书就行', '只做选择题'],
            '掌握英语知识的关键是：多练习、多运用、在语境中学习。语言是工具，只有通过大量的听说读写练习才能真正掌握。'
        );
        examples.push({ id: `${kid}_ex10`, knowledge_id: kid, question: q10.question, answer: q10.answer });

        allExamples.push(...examples);

        const filePath = path.join(EXAMPLES_DIR, `${kid}_010.json`);
        fs.writeFileSync(filePath, JSON.stringify(examples, null, 2), 'utf-8');
    });

    return allExamples;
}

function saveKnowledge(data, grade, subject, semester) {
    const filePath = path.join(KNOWLEDGE_DIR, `g${grade}_${subject}_${semester}.json`);
    const dataWithSemester = data.map((item, index) => {
        const semCode = semester === 'upper' ? 'u' : 'l';
        return {
            ...item,
            id: `g${grade}_${subject}_${semCode}${String(index + 1).padStart(3, '0')}`,
            semester: semester
        };
    });
    fs.writeFileSync(filePath, JSON.stringify(dataWithSemester, null, 2), 'utf-8');
    console.log(`已生成: g${grade}_${subject}_${semester}.json (${dataWithSemester.length}个知识点)`);
    return dataWithSemester;
}

const g1EnglishUpper = [
    { chapter: '上册 Unit 1', name: '问候与介绍', formula: 'Hello! / Hi! / Nice to meet you!', explanation: '【基本问候语】\n1. Hello! / Hi! 你好！\n2. Good morning! 早上好！\n3. Good afternoon! 下午好！\n4. Good evening! 晚上好！\n\n【自我介绍】\n1. I\'m... / My name is... 我是...\n2. I\'m from... 我来自...\n3. I\'m ... years old. 我...岁了\n\n【询问对方】\n1. What\'s your name? 你叫什么名字？\n2. Where are you from? 你来自哪里？\n3. How old are you? 你多大了？\n\n【告别语】\n1. Goodbye! / Bye! 再见！\n2. See you! 再见！\n3. See you tomorrow! 明天见！' },
    { chapter: '上册 Unit 1', name: '人称代词主格', formula: 'I, you, he, she, it, we, you, they', explanation: '【人称代词主格】\n作句子的主语，放在句首。\n\n【列表】\n- 第一人称单数：I（我）\n- 第二人称单数：you（你）\n- 第三人称单数：he（他）, she（她）, it（它）\n- 第一人称复数：we（我们）\n- 第二人称复数：you（你们）\n- 第三人称复数：they（他们/她们/它们）\n\n【用法】\n1. I am a student. 我是一名学生。\n2. He is from China. 他来自中国。\n3. They are my friends. 他们是我的朋友。\n\n【注意】\n- I（我）永远大写\n- you 既是"你"也是"你们"，谓语动词都用are\n- he/she/it 第三人称单数，谓语动词用is' },
    { chapter: '上册 Unit 1', name: 'be动词', formula: 'I am, you/we/they are, he/she/it is', explanation: '【be动词的三种形式】\nam, is, are\n\n【搭配口诀】\n我用am，你用are，\nis连着他、她、它，\n单数is，复数are。\n\n【例句】\n1. I am a teacher. 我是一名老师。\n2. You are my student. 你是我的学生。\n3. She is my sister. 她是我姐姐。\n4. We are classmates. 我们是同学。\n5. They are happy. 他们很开心。\n\n【缩写形式】\nI\'m = I am\nyou\'re = you are\nhe\'s = he is\nshe\'s = she is\nit\'s = it is\nwe\'re = we are\nthey\'re = they are' },
    { chapter: '上册 Unit 2', name: '家庭成员词汇', formula: 'father, mother, brother, sister, grandparent', explanation: '【核心词汇】\n1. family 家庭\n2. father (dad) 父亲（爸爸）\n3. mother (mom) 母亲（妈妈）\n4. parent 父亲或母亲\n5. parents 父母\n6. brother 哥哥/弟弟\n7. sister 姐姐/妹妹\n8. grandfather (grandpa) 祖父/外祖父\n9. grandmother (grandma) 祖母/外祖母\n10. grandparent 祖父/祖母/外祖父/外祖母\n11. grandparents 祖父母/外祖父母\n12. uncle 叔叔/舅舅/伯父\n13. aunt 阿姨/姑姑/婶婶\n14. cousin 堂（表）兄弟/姐妹\n\n【句型】\n1. This is my family. 这是我的家庭。\n2. These are my parents. 这是我的父母。\n3. I have a big family. 我有一个大家庭。' },
    { chapter: '上册 Unit 2', name: '指示代词', formula: 'this/that + 单数, these/those + 复数', explanation: '【指示代词】\n用来指示或标识人或事物的代词。\n\n【单数形式】\n- this（这，这个）：指近处的单数\n- that（那，那个）：指远处的单数\n\n【复数形式】\n- these（这些）：指近处的复数\n- those（那些）：指远处的复数\n\n【句型】\n1. This is my father. 这是我爸爸。\n2. That is my mother. 那是我妈妈。\n3. These are my parents. 这些是我的父母。\n4. Those are my friends. 那些是我的朋友。\n\n【一般疑问句】\n- Is this your sister? 这是你姐姐吗？\n  Yes, it is. / No, it isn\'t.\n- Are these your brothers? 这些是你哥哥吗？\n  Yes, they are. / No, they aren\'t.' },
    { chapter: '上册 Unit 2', name: '名词复数', formula: '一般加s，以s/x/ch/sh结尾加es', explanation: '【名词复数变化规则】\n\n1. 一般情况：直接加s\n   - book → books\n   - pen → pens\n\n2. 以s, x, ch, sh结尾：加es\n   - bus → buses\n   - box → boxes\n   - watch → watches\n   - dish → dishes\n\n3. 以辅音字母+y结尾：变y为i，加es\n   - baby → babies\n   - family → families\n\n4. 以f或fe结尾：变f/fe为v，加es\n   - knife → knives\n   - leaf → leaves\n\n5. 不规则变化：\n   - man → men\n   - woman → women\n   - child → children\n   - sheep → sheep（单复数同形）\n   - deer → deer（单复数同形）\n\n【注意】\n有些名词只有复数形式：clothes, people, police等' },
    { chapter: '上册 Unit 3', name: '物品与位置', formula: 'in/on/under/behind/near', explanation: '【常见物品词汇】\n1. schoolbag 书包\n2. book 书\n3. pen 钢笔\n4. pencil 铅笔\n5. ruler 尺子\n6. eraser 橡皮\n7. desk 书桌\n8. chair 椅子\n9. bed 床\n10. table 桌子\n\n【方位介词】\n1. in 在...里面\n2. on 在...上面\n3. under 在...下面\n4. behind 在...后面\n5. near 在...旁边\n6. next to 紧挨着\n7. in front of 在...前面\n8. between 在...之间\n\n【句型】\n- Where is the book? 书在哪里？\n  It\'s on the desk. 它在书桌上。\n- Where are the pens? 钢笔在哪里？\n  They\'re in the pencil box. 它们在铅笔盒里。' },
    { chapter: '上册 Unit 3', name: 'where引导的特殊疑问句', formula: 'Where + be + 主语?', explanation: '【where引导的特殊疑问句】\n用来询问地点和位置。\n\n【结构】\nWhere + be动词 + 主语？\n\n【单数形式】\n- Where is the book? 书在哪里？\n  It\'s on the desk. 它在书桌上。\n- Where is my schoolbag? 我的书包在哪里？\n  It\'s under the bed. 它在床下面。\n\n【复数形式】\n- Where are my keys? 我的钥匙在哪里？\n  They are on the table. 它们在桌子上。\n- Where are your books? 你的书在哪里？\n  They are in the schoolbag. 它们在书包里。\n\n【回答】\n- 单数用 It\'s... 回答\n- 复数用 They\'re... 回答' },
    { chapter: '上册 Unit 3', name: '物主代词', formula: 'my/your/his/her/its/our/your/their', explanation: '【形容词性物主代词】\n用在名词前面，起修饰作用，表示"谁的"。\n\n【列表】\n- 第一人称单数：my（我的）\n- 第二人称单数：your（你的）\n- 第三人称单数：his（他的）, her（她的）, its（它的）\n- 第一人称复数：our（我们的）\n- 第二人称复数：your（你们的）\n- 第三人称复数：their（他们的/她们的/它们的）\n\n【例句】\n1. This is my book. 这是我的书。\n2. That is your pen. 那是你的钢笔。\n3. His name is Tom. 他的名字是汤姆。\n4. Her sister is Lucy. 她姐姐是露西。\n5. Our classroom is big. 我们的教室很大。\n6. Their teacher is kind. 他们的老师很和蔼。' },
    { chapter: '上册 Unit 4', name: '日常活动', formula: 'get up, go to school, have class, do homework', explanation: '【常见日常活动】\n1. get up 起床\n2. eat breakfast 吃早饭\n3. go to school 去上学\n4. have class / have lessons 上课\n5. eat lunch 吃午饭\n6. play sports 做运动\n7. go home 回家\n8. do homework 做作业\n9. eat dinner 吃晚饭\n10. watch TV 看电视\n11. read a book 读书\n12. go to bed 睡觉\n\n【句型】\n- What time do you get up? 你几点起床？\n  I get up at 6:30. 我6:30起床。\n- When do you go to school? 你什么时候去上学？\n  I go to school at 7:30. 我7:30去上学。\n\n【一天的时间顺序】\n早上 → 上午 → 中午 → 下午 → 晚上' },
    { chapter: '上册 Unit 4', name: '一般现在时', formula: '主语 + 动词原形 / 动词三单形式', explanation: '【一般现在时定义】\n表示经常性、习惯性的动作或存在的状态。\n\n【构成】\n1. 肯定句：\n   - 第一/二人称/复数：主语 + 动词原形\n   - 第三人称单数：主语 + 动词三单形式\n\n2. 否定句：\n   - 主语 + don\'t/doesn\'t + 动词原形\n\n3. 一般疑问句：\n   - Do/Does + 主语 + 动词原形？\n\n【动词第三人称单数变化】\n1. 一般加s：work → works\n2. 以s/x/ch/sh/o结尾加es：go → goes\n3. 以辅音字母+y结尾：变y为i加es，study → studies\n4. 特殊变化：have → has\n\n【时间标志词】\nalways, usually, often, sometimes, every day, every morning等' },
    { chapter: '上册 Unit 4', name: '动词第三人称单数', formula: '一般加s，以s/x/ch/sh/o结尾加es', explanation: '【动词三单变化规则】\n\n1. 一般情况：直接加s\n   - work → works\n   - play → plays\n   - read → reads\n\n2. 以s, x, ch, sh, o结尾：加es\n   - pass → passes\n   - fix → fixes\n   - watch → watches\n   - wash → washes\n   - go → goes\n   - do → does\n\n3. 以辅音字母+y结尾：变y为i，加es\n   - study → studies\n   - fly → flies\n   - try → tries\n\n4. 不规则变化：\n   - have → has\n   - be → is\n\n【用法】\n当主语是he, she, it或单数名词时，动词用三单形式。\n例句：\n- He gets up early. 他起床很早。\n- She likes music. 她喜欢音乐。\n- It looks nice. 它看起来不错。' },
    { chapter: '上册 Unit 5', name: '食物与饮料', formula: 'food: rice, bread, meat; drink: water, milk, juice', explanation: '【食物词汇】\n1. rice 米饭\n2. bread 面包\n3. noodle 面条\n4. egg 鸡蛋\n5. meat 肉\n6. chicken 鸡肉\n7. fish 鱼肉\n8. vegetable 蔬菜\n9. fruit 水果\n10. apple 苹果\n11. banana 香蕉\n12. orange 橙子\n\n【饮料词汇】\n1. water 水\n2. milk 牛奶\n3. juice 果汁\n4. tea 茶\n5. coffee 咖啡\n6. coke/coca cola 可乐\n\n【三餐词汇】\n1. breakfast 早餐\n2. lunch 午餐\n3. dinner 晚餐\n4. meal 一餐\n\n【句型】\n- What would you like? 你想要什么？\n  I\'d like some rice. 我想要些米饭。\n- Do you like fish? 你喜欢鱼吗？\n  Yes, I do. / No, I don\'t.' },
    { chapter: '上册 Unit 5', name: '可数名词与不可数名词', formula: '可数：a/an + 单数; 不可数：不能用a/an，不能加s', explanation: '【可数名词】\n可以用数字计数的名词，有单数和复数形式。\n- a book → two books\n- an apple → three apples\n\n【不可数名词】\n不能直接用数字计数的名词，没有复数形式。\n常见不可数名词：\n- 液体：water, milk, juice, tea, coffee\n- 食物：rice, bread, meat, fish, fruit\n- 其他：paper, news, weather, advice, information\n\n【量词的使用】\n不可数名词要表示"多少"时，需要用量词。\n- a cup of tea 一杯茶\n- two glasses of water 两杯水\n- three pieces of bread 三片面包\n- a bottle of milk 一瓶牛奶\n\n【注意】\n- some/any 既可修饰可数名词，也可修饰不可数名词\n- many 修饰可数名词复数\n- much 修饰不可数名词' },
    { chapter: '上册 Unit 5', name: 'some与any', formula: 'some用于肯定句，any用于否定句和疑问句', explanation: '【some的用法】\n意思：一些，若干\n\n1. 用于肯定句\n   - I have some books. 我有一些书。\n   - There is some water in the glass. 杯子里有一些水。\n\n2. 用于表示请求或建议的疑问句中（希望得到肯定回答）\n   - Would you like some tea? 你想要些茶吗？\n   - Can I have some milk? 我能喝点牛奶吗？\n\n【any的用法】\n意思：一些，任何\n\n1. 用于否定句\n   - I don\'t have any pens. 我没有钢笔。\n   - There isn\'t any bread on the plate. 盘子里没有面包。\n\n2. 用于疑问句\n   - Do you have any questions? 你有问题吗？\n   - Is there any milk in the fridge? 冰箱里有牛奶吗？\n\n3. 用于肯定句中，表示"任何的"\n   - You can take any book. 你可以拿任何一本书。\n\n【修饰可数/不可数】\nsome和any都可以修饰可数名词复数和不可数名词。' },
    { chapter: '上册 Unit 6', name: '服装词汇', formula: 'shirt, T-shirt, jacket, coat, pants, shoes', explanation: '【服装词汇】\n1. shirt 衬衫（男）\n2. T-shirt T恤衫\n3. sweater 毛衣\n4. jacket 夹克衫\n5. coat 外套，大衣\n6. dress 连衣裙\n7. skirt 短裙\n8. pants / trousers 裤子\n9. jeans 牛仔裤\n10. shorts 短裤\n11. shoes 鞋子\n12. socks 袜子\n13. hat 帽子\n14. cap 鸭舌帽\n15. scarf 围巾\n16. gloves 手套\n\n【描述服装】\n1. 颜色：red, blue, green, yellow, black, white, purple, pink, orange, brown, gray\n2. 大小：big, small, long, short\n3. 新旧：new, old\n\n【句型】\n- What do you want to wear? 你想穿什么？\n  I want to wear a blue T-shirt. 我想穿一件蓝色T恤。\n- How much is the dress? 这条裙子多少钱？\n  It\'s 100 yuan. 100元。' },
    { chapter: '上册 Unit 6', name: 'how much与how many', formula: 'how much问不可数/价格，how many问可数数量', explanation: '【how many】\n意思：多少\n用法：对可数名词的数量提问，后面跟可数名词复数。\n\n例句：\n- How many books do you have? 你有多少本书？\n  I have five books. 我有五本书。\n- How many students are there in your class? 你们班有多少学生？\n  There are 40 students. 有40个学生。\n\n【how much】\n意思：多少；多少钱\n\n用法1：对不可数名词的数量提问\n- How much water is there in the bottle? 瓶子里有多少水？\n  There is some water. 有一些水。\n\n用法2：询问价格\n- How much is the pen? 这支钢笔多少钱？\n  It\'s five yuan. 五元。\n- How much are these shoes? 这双鞋多少钱？\n  They are 100 yuan. 100元。\n\n【总结】\n- how many + 可数名词复数\n- how much + 不可数名词 / 询问价格' },
    { chapter: '上册 Unit 7', name: '时间与日期', formula: 'What time is it? / What date is it today?', explanation: '【时间表达法】\n\n1. 直接表达：小时 + 分钟\n   - 6:30 → six thirty\n   - 7:15 → seven fifteen\n\n2. 逆读法：\n   - 分钟≤30：分钟 + past + 小时（几点过几分）\n     - 6:10 → ten past six\n   - 分钟>30：(60-分钟) + to + (小时+1)（差几分到几点）\n     - 6:50 → ten to seven\n   - 30分钟用half：6:30 → half past six\n   - 15分钟用a quarter：6:15 → a quarter past six\n\n【日期表达】\n1. What day is it today? 今天星期几？\n   It\'s Monday. 今天星期一。\n\n2. What\'s the date today? 今天几月几号？\n   It\'s June 1st. 今天6月1日。\n\n【星期】\nMonday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday\n\n【月份】\nJanuary, February, March, April, May, June, July, August, September, October, November, December' },
    { chapter: '上册 Unit 7', name: '介词in/on/at表时间', formula: 'in年/月/季节，on具体某天，at具体时刻', explanation: '【in的用法】\n用于较长的时间段\n1. 年：in 2024 在2024年\n2. 月：in June 在六月\n3. 季节：in spring 在春天\n4. 上午/下午/晚上：in the morning 在早上\n\n【on的用法】\n用于具体的某一天或某一天的上午、下午、晚上\n1. 具体日期：on June 1st 在6月1日\n2. 星期：on Monday 在星期一\n3. 具体某天的上午：on Monday morning 在星期一早上\n4. 节日：on Children\'s Day 在儿童节\n\n【at的用法】\n用于具体的时刻或较短的时间\n1. 具体时间：at 7:30 在7点半\n2. 中午/夜晚：at noon 在中午，at night 在晚上\n3. 节日：at Christmas 在圣诞节期间\n4. 年龄：at the age of 10 在10岁时\n\n【固定搭配】\nin the morning/afternoon/evening\nat noon/night\non weekdays/weekends' },
    { chapter: '上册 Unit 8', name: '天气', formula: 'sunny, rainy, cloudy, windy, snowy', explanation: '【天气词汇（形容词）】\n1. sunny 晴朗的\n2. rainy 下雨的\n3. cloudy 多云的，阴天的\n4. windy 有风的\n5. snowy 下雪的\n6. hot 热的\n7. cold 冷的\n8. warm 温暖的\n9. cool 凉爽的\n\n【名词形式】\n1. sun 太阳 / 阳光\n2. rain 雨 / 下雨\n3. cloud 云\n4. wind 风\n5. snow 雪 / 下雪\n\n【询问天气】\n1. What\'s the weather like today? 今天天气怎么样？\n   It\'s sunny. 今天是晴天。\n\n2. How is the weather? 天气怎么样？\n   It\'s raining. 正在下雨。\n\n【描述天气】\n- It\'s a nice day today. 今天是个好天气。\n- It is going to rain tomorrow. 明天会下雨。\n- The sun is shining. 阳光灿烂。\n\n【注意】\n- 描述天气常用 It 作主语\n- be + 形容词：It\'s sunny.\n- be + 动词ing：It\'s raining.' },
    { chapter: '上册 Unit 8', name: '现在进行时', formula: 'be + 动词ing，表示正在进行的动作', explanation: '【定义】\n表示现在正在进行或发生的动作。\n\n【构成】\n肯定句：主语 + am/is/are + 动词ing\n否定句：主语 + am/is/are + not + 动词ing\n一般疑问句：Am/Is/Are + 主语 + 动词ing？\n\n【动词ing变化规则】\n1. 一般直接加ing：play → playing\n2. 以不发音的e结尾：去e加ing，make → making\n3. 重读闭音节（辅元辅）：双写最后字母加ing，run → running\n4. 以ie结尾：变ie为y加ing，lie → lying\n\n【时间标志词】\nnow, look, listen, at the moment, these days等\n\n【例句】\n- I am reading a book now. 我现在正在看书。\n- Listen! The birds are singing. 听！鸟儿在唱歌。\n- Look! They are playing football. 看！他们在踢足球。\n\n【特殊变化】\nsit → sitting\nshop → shopping\nswim → swimming\nrun → running\nput → putting' },
    { chapter: '上册 Unit 9', name: '学校生活', formula: 'subjects: English, math, Chinese, PE, music, art', explanation: '【学校课程】\n1. English 英语\n2. math 数学\n3. Chinese 语文\n4. PE / physical education 体育\n5. music 音乐\n6. art 美术\n7. science 科学\n8. history 历史\n9. geography 地理\n10. biology 生物\n\n【学校场所】\n1. classroom 教室\n2. playground 操场\n3. library 图书馆\n4. lab / laboratory 实验室\n5. canteen / dining hall 食堂\n6. teachers\' office 教师办公室\n7. gym 体育馆\n8. garden 花园\n\n【句型】\n- What subject do you like best? 你最喜欢什么科目？\n  I like English best. 我最喜欢英语。\n- What class do you have on Monday? 你星期一有什么课？\n  I have English, math and P.E. 我有英语、数学和体育。\n- How many classes do you have every day? 你每天有几节课？\n  I have six classes. 我有六节课。' },
    { chapter: '上册 Unit 9', name: '形容词', formula: '形容词修饰名词，放在名词前或be动词后', explanation: '【形容词定义】\n用来修饰名词或代词，表示人或事物的性质、状态、特征等。\n\n【用法】\n1. 放在名词前面，作定语\n   - a big apple 一个大苹果\n   - a beautiful girl 一个漂亮的女孩\n\n2. 放在be动词/系动词后面，作表语\n   - The apple is big. 苹果很大。\n   - She looks happy. 她看起来很开心。\n\n【常见形容词】\n1. 大小：big, small, long, short, tall\n2. 颜色：red, blue, green, yellow, black, white\n3. 品质：good, bad, nice, kind, clever\n4. 感受：happy, sad, angry, tired, excited\n5. 天气：sunny, rainy, hot, cold, warm\n6. 年龄：old, young, new\n\n【形容词排序】\n多个形容词修饰名词时的顺序：\n限定词 → 描绘 → 大小 → 形状 → 年龄 → 颜色 → 国籍 → 材料 → 用途 + 名词' },
    { chapter: '上册 语法', name: '定冠词the', formula: 'the + 名词，表特指', explanation: '【定冠词the的用法】\n\n1. 特指某(些)人或某(些)物\n   - The book on the desk is mine. 书桌上那本书是我的。\n\n2. 指双方都知道的人或物\n   - Open the door, please. 请开门。\n\n3. 复述上文提到的人或物\n   - I have a cat. The cat is white. 我有一只猫，这只猫是白色的。\n\n4. 世界上独一无二的事物\n   - the sun 太阳，the moon 月亮，the earth 地球\n\n5. 用在序数词和形容词最高级前\n   - the first lesson 第一课，the tallest student 最高的学生\n\n6. 用在某些固定词组中\n   - in the morning 在早上\n   - at the same time 同时\n   - by the way 顺便说一下\n\n【不用冠词的情况】\n1. 泛指的复数名词前\n2. 专有名词前（人名、地名等）\n3. 星期、月份、节假日前\n4. 球类运动、棋类前\n5. 学科前' },
    { chapter: '上册 语法', name: '不定冠词a/an', formula: 'a + 辅音开头, an + 元音开头', explanation: '【不定冠词的用法】\na和an都是不定冠词，意思是"一（个，只...）"，用在单数可数名词前。\n\n【a和an的区别】\n1. a 用在辅音音素开头的单词前\n   - a book 一本书\n   - a pen 一支钢笔\n   - a student 一名学生\n   - a university 一所大学（u发/ju:/是辅音）\n\n2. an 用在元音音素开头的单词前\n   - an apple 一个苹果\n   - an egg 一个鸡蛋\n   - an hour 一小时（h不发音）\n   - an English book 一本英语书\n\n【用法】\n1. 泛指某一类人或物中的一个\n   - I am a student. 我是一名学生。\n\n2. 第一次提到某人或某物\n   - There is a book on the desk. 书桌上有一本书。\n\n3. 表示"每一"，相当于every\n   - We have six classes a day. 我们一天有六节课。\n\n4. 用在某些固定词组中\n   - a lot of 许多，a few 几个，a little 一点' },
    { chapter: '上册 语法', name: 'There be句型', formula: 'There is + 单数, There are + 复数', explanation: '【There be句型】\n表示"某地有某物/某人"。\n\n【构成】\n肯定句：There + is/are + 名词 + 地点\n否定句：There + is/are + not + 名词 + 地点\n一般疑问句：Is/Are + there + 名词 + 地点？\n\n【主谓一致】\nThere be句型中，be动词要和后面的第一个名词保持一致（就近原则）。\n\n【例句】\n- There is a book on the desk. 书桌上有一本书。\n- There are some books on the desk. 书桌上有一些书。\n- There is a pen and two pencils in the pencil-box. 铅笔盒里有一支钢笔和两支铅笔。\n- There are two pencils and a pen in the pencil-box. 铅笔盒里有两支铅笔和一支钢笔。\n\n【一般疑问句及回答】\n- Is there a library in your school? 你们学校有图书馆吗？\n  Yes, there is. / No, there isn\'t.\n- Are there any students in the classroom? 教室里有学生吗？\n  Yes, there are. / No, there aren\'t.\n\n【特殊疑问句】\nHow many + 名词复数 + are there + 地点？' },
    { chapter: '上册 语法', name: '特殊疑问句', formula: '特殊疑问词 + 一般疑问句语序', explanation: '【定义】\n以特殊疑问词开头的疑问句叫做特殊疑问句。回答时不用yes/no，要具体回答。\n\n【常见特殊疑问词】\n1. what（什么）：问事物、职业、名字等\n2. who（谁）：问人\n3. whose（谁的）：问所属\n4. where（在哪里）：问地点\n5. when / what time（什么时候）：问时间\n6. why（为什么）：问原因\n7. how（怎样）：问方式、状态\n8. how old（多大）：问年龄\n9. how many（多少）：问数量（可数）\n10. how much（多少/多少钱）：问数量（不可数）或价格\n11. which（哪一个）：问选择\n12. what color（什么颜色）：问颜色\n\n【例句】\n- What is your name? 你叫什么名字？\n  My name is Tom. 我叫汤姆。\n- Where do you live? 你住在哪里？\n  I live in Beijing. 我住在北京。\n- How old are you? 你多大了？\n  I am 12 years old. 我12岁。\n- Why are you late? 你为什么迟到？\n  Because I got up late. 因为我起晚了。' },
    { chapter: '上册 语法', name: '名词所有格', formula: '单数加\'s，复数s结尾加\'', explanation: '【名词所有格】\n表示有生命的东西的名词的所有关系。\n\n【构成方法】\n\n1. 单数名词加\'s\n   - Tom\'s book 汤姆的书\n   - the girl\'s bike 女孩的自行车\n   - my mother\'s bag 我妈妈的包\n\n2. 以s结尾的复数名词加\'\n   - the students\' classroom 学生们的教室\n   - Teachers\' Day 教师节\n   - two hours\' walk 两小时的步行路程\n\n3. 不以s结尾的复数名词加\'s\n   - Children\'s Day 儿童节\n   - men\'s room 男厕所\n   - women\'s clothes 女人的衣服\n\n4. 共同所有和分别所有\n   - Tom and Mike\'s room 汤姆和迈克的房间（共同拥有，一间房）\n   - Tom\'s and Mike\'s rooms 汤姆的房间和迈克的房间（分别拥有，两间房）\n\n【注意】\n1. 无生命的东西的所有关系一般用 of 短语\n   - the door of the room 房间的门\n2. 表示时间、距离、国家等的名词也可用\'s\n   - today\'s newspaper 今天的报纸' },
    { chapter: '上册 语法', name: '基数词', formula: 'one, two, three... 表示数量多少', explanation: '【基数词定义】\n表示数量多少的数词叫基数词。\n\n【1-100基数词】\n1-12: one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve\n\n13-19: 以-teen结尾\nthirteen, fourteen, fifteen, sixteen, seventeen, eighteen, nineteen\n\n20-90整十：以-ty结尾\ntwenty, thirty, forty, fifty, sixty, seventy, eighty, ninety\n\n几十几：几十 + "-" + 几\n21 → twenty-one\n35 → thirty-five\n99 → ninety-nine\n\n100 → one hundred\n\n【用法】\n1. 表示数量：three books 三本书\n2. 表示年龄：ten years old 十岁\n3. 表示时间：eight o\'clock 八点钟\n4. 表示价格：five yuan 五元\n\n【注意】\n- hundred前有具体数字时，不加s\n- 模糊数量用 hundreds of（成百上千的）' },
    { chapter: '上册 语法', name: '序数词', formula: 'first, second, third... 表示顺序第几', explanation: '【序数词定义】\n表示顺序的数词叫序数词，意思是"第几"。\n\n【构成规则】\n1. 一般在基数词后加th\n   four → fourth 第四\n   six → sixth 第六\n\n2. 特殊变化（1、2、3）\n   one → first 第一\n   two → second 第二\n   three → third 第三\n\n3. 以ve结尾的，变ve为f加th\n   five → fifth 第五\n   twelve → twelfth 第十二\n\n4. 以ty结尾的整十数，变y为ie加th\n   twenty → twentieth 第二十\n   thirty → thirtieth 第三十\n\n5. 几十几的序数词，只变个位，十位不变\n   twenty-one → twenty-first 第二十一\n   thirty-five → thirty-fifth 第三十五\n\n【缩写形式】\n阿拉伯数字 + 序数词最后两个字母\n1st, 2nd, 3rd, 4th, 5th...\n\n【用法】\n1. 表示顺序：the first lesson 第一课\n2. 表示日期：June 1st 6月1日\n3. 表示楼层：on the second floor 在二楼\n\n【注意】\n序数词前面一般要加定冠词the' },
];

const g1EnglishLower = [
    { chapter: '下册 Unit 1', name: '问路与交通', formula: 'Go straight. Turn left. Turn right.', explanation: '【交通方式】\n1. by bus 乘公共汽车\n2. by car 乘小汽车\n3. by bike 骑自行车\n4. on foot 步行\n5. by train 乘火车\n6. by plane / by air 乘飞机\n7. by ship / by sea 乘船\n8. take the subway 乘地铁\n\n【问路常用语】\n1. Excuse me, where is...? 打扰一下，...在哪里？\n2. How can I get to...? 我怎么去...？\n3. Which is the way to...? 哪条路是去...的？\n4. Is there a ... near here? 这附近有...吗？\n\n【指路常用语】\n1. Go straight. 直走。\n2. Turn left. 向左转。\n3. Turn right. 向右转。\n4. Go along this street. 沿着这条街走。\n5. It\'s on your left/right. 在你的左/右边。\n6. You can\'t miss it. 你不会错过的。\n\n【句型】\n- How do you go to school? 你怎么去上学？\n  I go to school by bike. 我骑自行车去上学。' },
    { chapter: '下册 Unit 1', name: '情态动词can', formula: 'can + 动词原形，表示能、会、可以', explanation: '【定义】\ncan是情态动词，表示"能够、可以、会"。\n\n【用法】\n1. 表示能力（会，能够）\n   - I can swim. 我会游泳。\n   - Can you speak English? 你会说英语吗？\n\n2. 表示许可（可以）\n   - Can I use your pen? 我可以用你的钢笔吗？\n   - Yes, you can. / No, you can\'t.\n\n3. 表示推测（可能）\n   - That can\'t be true. 那不可能是真的。\n\n【结构】\n肯定句：主语 + can + 动词原形\n否定句：主语 + can\'t (cannot) + 动词原形\n一般疑问句：Can + 主语 + 动词原形？\n\n【回答】\n- Can you play football? 你会踢足球吗？\n  Yes, I can. / No, I can\'t.\n\n【注意】\n1. can没有人称和数的变化\n2. 后面跟动词原形\n3. 过去式是could' },
    { chapter: '下册 Unit 1', name: '祈使句', formula: '动词原形开头，表示命令、请求、建议', explanation: '【定义】\n祈使句用来表示请求、命令、劝告、警告等。主语you通常省略。\n\n【肯定形式】\n1. 动词原形 + 其他\n   - Stand up, please. 请起立。\n   - Open the door. 开门。\n   - Be quiet. 安静。\n   - Let\'s go. 咱们走吧。\n\n2. Let型：Let + 宾语 + 动词原形\n   - Let me help you. 让我来帮你。\n   - Let\'s play football. 我们踢足球吧。\n\n【否定形式】\n1. Don\'t + 动词原形\n   - Don\'t be late. 不要迟到。\n   - Don\'t talk in class. 不要在课堂上讲话。\n\n2. Let型的否定：Don\'t let + 宾语 + 动词原形 / Let + 宾语 + not + 动词原形\n   - Don\'t let him go. / Let him not go. 别让他走。\n\n【表示礼貌】\n句首或句尾加please\n- Please sit down. / Sit down, please. 请坐。\n\n【注意】\n1. 祈使句的否定一律用Don\'t开头（Let型除外）\n2. 动词永远用原形' },
    { chapter: '下册 Unit 2', name: '周末活动', formula: 'watch TV, play sports, go shopping, visit friends', explanation: '【周末活动词汇】\n1. watch TV 看电视\n2. read books / do some reading 看书\n3. play sports 做运动\n4. play football / basketball 踢足球/打篮球\n5. go swimming 去游泳\n6. go shopping 去购物\n7. go to the park 去公园\n8. go to the cinema / see a movie 去看电影\n9. visit grandparents 看望祖父母\n10. visit friends 拜访朋友\n11. do homework 做作业\n12. clean the room 打扫房间\n13. wash clothes 洗衣服\n14. listen to music 听音乐\n15. draw pictures 画画\n\n【句型】\n- What do you usually do on weekends? 你周末通常做什么？\n  I usually play football with my friends. 我通常和朋友们踢足球。\n- What are you going to do this weekend? 这个周末你打算做什么？\n  I\'m going to visit my grandma. 我打算去看望奶奶。\n- How was your weekend? 你周末过得怎么样？\n  It was great. 很棒。' },
    { chapter: '下册 Unit 2', name: '一般将来时', formula: 'will + 动词原形 / be going to + 动词原形', explanation: '【定义】\n表示将来某个时间要发生的动作或存在的状态。\n\n【构成方式一：will + 动词原形】\n肯定句：主语 + will + 动词原形\n否定句：主语 + will not (won\'t) + 动词原形\n一般疑问句：Will + 主语 + 动词原形？\n\n例句：\n- I will visit my grandma tomorrow. 我明天要去看望奶奶。\n- Will you go with us? 你和我们一起去吗？\n  Yes, I will. / No, I won\'t.\n\n【构成方式二：be going to + 动词原形】\n表示计划、打算做某事，或根据迹象判断将要发生。\n肯定句：主语 + am/is/are + going to + 动词原形\n\n例句：\n- I\'m going to play football this afternoon. 我今天下午打算踢足球。\n- It\'s going to rain. 要下雨了。\n\n【时间标志词】\ntomorrow, next week, next month, soon, in the future, this weekend等\n\n【shall的用法】\nshall用于第一人称，表示建议或征求对方意见：\n- Shall we go? 我们走好吗？' },
    { chapter: '下册 Unit 2', name: '一般过去时', formula: '主语 + 动词过去式', explanation: '【定义】\n表示过去某个时间发生的动作或存在的状态。\n\n【构成】\n肯定句：主语 + 动词过去式\n否定句：主语 + didn\'t + 动词原形\n一般疑问句：Did + 主语 + 动词原形？\n\n【动词过去式变化规则】\n\n1. 一般直接加ed\n   - work → worked\n   - play → played\n\n2. 以不发音的e结尾加d\n   - like → liked\n   - live → lived\n\n3. 以辅音字母+y结尾：变y为i加ed\n   - study → studied\n   - carry → carried\n\n4. 重读闭音节（辅元辅）：双写最后字母加ed\n   - stop → stopped\n   - plan → planned\n\n【不规则变化（常见）】\nam/is → was\nare → were\ngo → went\ncome → came\ndo → did\nhave → had\nsee → saw\nsay → said\nget → got\nmake → made\n\n【时间标志词】\nyesterday, last week, last month, last year, ago, just now等' },
    { chapter: '下册 Unit 3', name: '动物', formula: 'animals: panda, tiger, lion, elephant, monkey', explanation: '【常见动物】\n\n【哺乳动物】\n1. panda 熊猫\n2. tiger 老虎\n3. lion 狮子\n4. elephant 大象\n5. monkey 猴子\n6. bear 熊\n7. wolf 狼\n8. fox 狐狸\n9. rabbit 兔子\n10. deer 鹿\n11. horse 马\n12. cow 奶牛\n13. sheep 绵羊\n14. pig 猪\n15. dog 狗\n16. cat 猫\n\n【鸟类】\n1. bird 鸟\n2. eagle 鹰\n3. parrot 鹦鹉\n4. swan 天鹅\n5. chicken 鸡\n6. duck 鸭\n\n【其他】\n1. fish 鱼\n2. snake 蛇\n3. frog 青蛙\n4. turtle 乌龟\n5. butterfly 蝴蝶\n6. bee 蜜蜂\n\n【句型】\n- What\'s your favorite animal? 你最喜欢的动物是什么？\n  My favorite animal is the panda. 我最喜欢的动物是熊猫。\n- Where do pandas live? 熊猫住在哪里？\n  They live in China. 它们住在中国。' },
    { chapter: '下册 Unit 3', name: '形容词比较级', formula: 'A + be + 比较级 + than + B', explanation: '【定义】\n表示两者（人或事物）的比较，"...比...更..."。\n\n【构成规则】\n\n1. 一般单音节词加er\n   - tall → taller\n   - long → longer\n\n2. 以不发音的e结尾加r\n   - nice → nicer\n   - large → larger\n\n3. 以辅音字母+y结尾：变y为i加er\n   - happy → happier\n   - easy → easier\n\n4. 重读闭音节（辅元辅）：双写最后字母加er\n   - big → bigger\n   - hot → hotter\n   - thin → thinner\n\n5. 多音节词和部分双音节词：在前面加more\n   - beautiful → more beautiful\n   - interesting → more interesting\n\n【不规则变化】\ngood/well → better\nbad/ill → worse\nmany/much → more\nlittle → less\nfar → farther/further\n\n【基本句型】\nA + be + 形容词比较级 + than + B\n- Tom is taller than Mike. 汤姆比迈克高。\n- This book is more interesting than that one. 这本书比那本更有趣。' },
    { chapter: '下册 Unit 3', name: '形容词最高级', formula: 'A + be + the + 最高级 + of/in...', explanation: '【定义】\n表示三者或三者以上的人或事物的比较，"...最..."。\n\n【构成规则】\n\n1. 一般单音节词加est\n   - tall → tallest\n   - long → longest\n\n2. 以不发音的e结尾加st\n   - nice → nicest\n   - large → largest\n\n3. 以辅音字母+y结尾：变y为i加est\n   - happy → happiest\n   - easy → easiest\n\n4. 重读闭音节（辅元辅）：双写最后字母加est\n   - big → biggest\n   - hot → hottest\n\n5. 多音节词：在前面加most\n   - beautiful → most beautiful\n   - interesting → most interesting\n\n【不规则变化】\ngood/well → best\nbad/ill → worst\nmany/much → most\nlittle → least\nfar → farthest/furthest\n\n【基本句型】\nA + be + the + 形容词最高级 + of/in...\n- Tom is the tallest in our class. 汤姆是我们班最高的。\n- This is the most interesting book of the three. 这是三本书中最有趣的。\n\n【注意】\n形容词最高级前面一般要加定冠词the' },
    { chapter: '下册 Unit 4', name: '职业', formula: 'teacher, doctor, worker, farmer, driver', explanation: '【常见职业】\n1. teacher 老师\n2. doctor 医生\n3. nurse 护士\n4. worker 工人\n5. farmer 农民\n6. driver 司机\n7. cook 厨师\n8. policeman 警察\n9. soldier 士兵\n10. engineer 工程师\n11. singer 歌手\n12. dancer 舞蹈家\n13. writer 作家\n14. artist 艺术家\n15. scientist 科学家\n16. astronaut 宇航员\n17. businessman 商人\n18. reporter 记者\n19. lawyer 律师\n20. actor / actress 演员\n\n【句型】\n- What do you do? / What\'s your job? 你是做什么工作的？\n  I\'m a teacher. 我是一名老师。\n- What does your father do? 你爸爸是做什么的？\n  He is a doctor. 他是一名医生。\n- Where does your mother work? 你妈妈在哪里工作？\n  She works in a hospital. 她在医院工作。\n- What do you want to be? 你想成为什么样的人？\n  I want to be a scientist. 我想成为一名科学家。' },
    { chapter: '下册 Unit 4', name: '一般现在时第三人称单数', formula: '动词后加s/es', explanation: '【用法回顾】\n当主语是第三人称单数时，谓语动词要用第三人称单数形式。\n\n【第三人称单数主语】\n1. 人称代词：he, she, it\n2. 单个人名、地名：Tom, Beijing\n3. 单数名词：the book, my father\n4. 不定代词：everyone, someone, anyone, no one, something等\n\n【动词三单变化】\n1. 一般加s：works, plays, reads\n2. 以s, x, ch, sh, o结尾加es：goes, does, watches, washes, passes\n3. 以辅音字母+y结尾：变y为i加es：studies, flies, tries\n4. 不规则变化：have → has, be → is\n\n【句型转换】\n肯定句 → 否定句：主语 + doesn\'t + 动词原形\n- He likes apples. → He doesn\'t like apples.\n\n肯定句 → 一般疑问句：Does + 主语 + 动词原形？\n- She gets up early. → Does she get up early?\n  Yes, she does. / No, she doesn\'t.\n\n【记忆口诀】\n三单动词很重要，词尾常常加s/es；\n否定句中doesn\'t加，动词还原要记牢；\n疑问句中does当先，动词原形后边站。' },
    { chapter: '下册 Unit 5', name: '生日与节日', formula: 'birthday: When is your birthday? festival: Spring Festival', explanation: '【生日相关词汇】\n1. birthday 生日\n2. birthday cake 生日蛋糕\n3. birthday gift / present 生日礼物\n4. birthday party 生日派对\n5. birthday candle 生日蜡烛\n6. wish 愿望\n7. blow out 吹灭\n8. celebrate 庆祝\n\n【中国节日】\n1. Spring Festival 春节\n2. Lantern Festival 元宵节\n3. Dragon Boat Festival 端午节\n4. Mid-Autumn Festival 中秋节\n5. National Day 国庆节\n6. Children\'s Day 儿童节\n7. Teachers\' Day 教师节\n\n【西方节日】\n1. New Year\'s Day 元旦\n2. Christmas 圣诞节\n3. Halloween 万圣节\n4. Thanksgiving Day 感恩节\n5. Easter 复活节\n6. Valentine\'s Day 情人节\n\n【句型】\n- When is your birthday? 你的生日是什么时候？\n  My birthday is on October 1st. 我的生日在10月1日。\n- How do you celebrate your birthday? 你怎么庆祝生日？\n  I usually have a birthday party. 我通常举办生日派对。' },
    { chapter: '下册 Unit 5', name: '序数词', formula: 'first, second, third... 表示顺序', explanation: '【序数词定义】\n表示顺序先后的数词叫序数词。\n\n【基数词变序数词口诀】\n基变序，有规律，词尾加上th。\n一、二、三，特殊记，词尾字母t, d, d。\n八减t，九减e，f来把ve替。\n单词ty作结尾，ty变成tie。\n若是碰到几十几，只变个位就可以。\n\n【常见序数词】\n1st: first\n2nd: second\n3rd: third\n4th: fourth\n5th: fifth\n6th: sixth\n7th: seventh\n8th: eighth\n9th: ninth\n10th: tenth\n11th: eleventh\n12th: twelfth\n13th: thirteenth\n20th: twentieth\n21st: twenty-first\n30th: thirtieth\n100th: one hundredth\n\n【用法】\n1. 表示顺序：the first lesson 第一课\n2. 表示日期：June 1st 6月1日\n3. 表示楼层：on the second floor 在二楼\n4. 表示次数：for the first time 第一次\n\n【注意】\n序数词前面一般要加定冠词the' },
    { chapter: '下册 Unit 6', name: '描述人物', formula: 'tall, short, fat, thin, young, old, beautiful', explanation: '【外貌描述】\n1. 身高：tall 高的，short 矮的，of medium height 中等身高\n2. 体型：fat 胖的，thin 瘦的，heavy 重的，slim 苗条的，strong 强壮的\n3. 头发：long hair 长头发，short hair 短头发，straight hair 直发，curly hair 卷发，black hair 黑发，blonde hair 金发\n4. 眼睛：big eyes 大眼睛，small eyes 小眼睛\n5. 面容：round face 圆脸，long face 长脸\n\n【性格描述】\n1. kind 和蔼的，善良的\n2. friendly 友好的\n3. shy 害羞的\n4. outgoing 外向的\n5. clever / smart 聪明的\n6. lazy 懒惰的\n7. hard-working 勤奋的\n8. brave 勇敢的\n9. quiet 安静的\n10. funny 有趣的，滑稽的\n\n【句型】\n- What does he look like? 他长什么样？\n  He is tall and thin. 他又高又瘦。\n- What is she like? 她是什么样的人？\n  She is very kind and friendly. 她既善良又友好。\n- She has long straight hair. 她留着长长的直发。' },
    { chapter: '下册 Unit 6', name: '介词', formula: 'in, on, at, for, to, with, by, about', explanation: '【常见介词及用法】\n\n1. in（在...里面；在一段时间内）\n   - in the box 在盒子里\n   - in the morning 在早上\n   - in China 在中国\n\n2. on（在...上面；在具体某天）\n   - on the desk 在书桌上\n   - on Monday 在星期一\n\n3. at（在...时刻；在小地点）\n   - at 7 o\'clock 在7点\n   - at home 在家\n   - at the station 在车站\n\n4. for（为了；给；持续时间）\n   - a gift for you 给你的礼物\n   - for two hours 持续两小时\n\n5. to（到；向；给）\n   - go to school 去上学\n   - give sth. to sb. 把某物给某人\n\n6. with（和...一起；用；带有）\n   - play with friends 和朋友玩\n   - write with a pen 用钢笔写\n   - a girl with long hair 一个长发女孩\n\n7. by（乘；在...旁边；到...之前）\n   - by bus 乘公共汽车\n   - by the river 在河边\n   - by tomorrow 到明天为止\n\n8. about（关于；大约）\n   - a book about animals 一本关于动物的书\n   - about 100 people 大约100人' },
    { chapter: '下册 Unit 7', name: '过去的事', formula: '一般过去时描述过去发生的事情', explanation: '【一般过去时回顾】\n表示过去某个时间发生的动作或存在的状态。\n\n【常见过去式不规则变化】\nbe → was/were\nbegin → began\nbring → brought\nbuy → bought\ncome → came\ndo → did\neat → ate\nfeel → felt\nfind → found\nfly → flew\nforget → forgot\nget → got\ngo → went\nhave → had\nkeep → kept\nknow → knew\nleave → left\nmake → made\nmeet → met\nread → read（读音不同）\nrun → ran\nsay → said\nsee → saw\nsing → sang\nsit → sat\nspeak → spoke\nspend → spent\nstand → stood\nswim → swam\ntake → took\nteach → taught\ntell → told\nthink → thought\nwrite → wrote\n\n【描述过去经历的句型】\n- Last summer, I went to Beijing with my parents. 去年夏天，我和父母去了北京。\n- We visited the Great Wall. 我们参观了长城。\n- I had a good time there. 我在那里玩得很开心。' },
    { chapter: '下册 Unit 7', name: '动词过去式的规则变化', formula: '一般加ed，以e结尾加d，辅y结尾变i加ed', explanation: '【规则动词过去式变化】\n\n1. 一般情况：直接加ed\n   - work → worked\n   - play → played\n   - start → started\n   - need → needed\n\n2. 以不发音的字母e结尾：加d\n   - like → liked\n   - live → lived\n   - use → used\n   - dance → danced\n\n3. 以辅音字母加y结尾：变y为i，再加ed\n   - study → studied\n   - carry → carried\n   - try → tried\n   - worry → worried\n\n4. 重读闭音节（辅元辅结构）末尾只有一个辅音字母：双写这个辅音字母，再加ed\n   - stop → stopped\n   - plan → planned\n   - shop → shopped\n   - drop → dropped\n\n【ed的读音】\n1. 在清辅音后读/t/：helped, washed, watched\n2. 在浊辅音和元音后读/d/：played, lived, called\n3. 在t/d后读/ɪd/：wanted, needed, visited\n\n【不规则变化】\n需要单独记忆，约有200多个不规则动词。' },
    { chapter: '下册 Unit 8', name: '计划与打算', formula: 'be going to / will + 动词原形', explanation: '【表示计划与打算的方式】\n\n1. be going to + 动词原形\n   表示事先考虑好的计划、打算。\n   - I\'m going to visit my grandma this weekend. 这个周末我打算去看望奶奶。\n   - What are you going to do tomorrow? 你明天打算做什么？\n\n2. will + 动词原形\n   表示将来要发生的事，常带意愿色彩。\n   - I will help you with your English. 我会帮你学英语的。\n   - I won\'t be late again. 我不会再迟到了。\n\n3. 现在进行时表将来\n   某些表示位置移动的动词（come, go, leave, arrive等），用现在进行时表示计划好的事情。\n   - We are leaving for Beijing tomorrow. 我们明天要去北京。\n   - He is coming this afternoon. 他今天下午要来。\n\n4. plan to do sth.\n   计划做某事\n   - I plan to go to the park this Sunday. 我计划这个周日去公园。\n\n5. want to do sth.\n   想要做某事\n   - I want to be a scientist when I grow up. 我长大了想当科学家。' },
    { chapter: '下册 Unit 8', name: 'want / would like', formula: 'want to do / would like to do', explanation: '【want的用法】\n意思：想要\n\n1. want + 名词：想要某物\n   - I want a new book. 我想要一本新书。\n   - Do you want some tea? 你想要些茶吗？\n\n2. want to do sth.：想要做某事\n   - I want to play football. 我想去踢足球。\n   - She wants to be a doctor. 她想成为一名医生。\n\n3. want sb. to do sth.：想要某人做某事\n   - I want you to help me. 我想要你帮我。\n   - Mom wants me to study hard. 妈妈想要我努力学习。\n\n【would like的用法】\n意思：想要（比want更委婉）\n\n1. would like + 名词\n   - I would like some noodles. = I\'d like some noodles. 我想要些面条。\n   - Would you like some tea? 你想要些茶吗？\n   Yes, please. / No, thanks.\n\n2. would like to do sth.\n   - I would like to go with you. 我想和你一起去。\n   - Would you like to go swimming with us? 你想和我们一起去游泳吗？\n\n【注意】\n1. would like没有人称和数的变化\n2. 疑问句中表示委婉请求，some不变any' },
    { chapter: '下册 语法', name: '现在进行时表将来', formula: 'come/go/leave/arrive的进行时表将来', explanation: '【用法】\n某些表示位置移动的动词，可以用现在进行时表示按计划或安排将要发生的动作。\n\n【常见动词】\n1. come 来\n2. go 去\n3. leave 离开\n4. arrive 到达\n5. start 开始\n6. fly 飞\n7. move 移动\n8. return 返回\n\n【例句】\n- The train is arriving soon. 火车马上就要到了。\n- We are leaving for Shanghai tomorrow. 我们明天要去上海。\n- He is coming to see you this afternoon. 他今天下午要来看你。\n- The plane is taking off in five minutes. 飞机五分钟后就要起飞了。\n\n【与be going to的区别】\n1. 现在进行时表将来：多指已经安排好的，位置移动类的动词\n2. be going to：多指计划、打算做的事，或根据迹象判断\n\n【注意】\n- 这种用法常用于口语中\n- 常配有表示将来的时间状语，如 tomorrow, next week, soon等' },
    { chapter: '下册 语法', name: '介词短语', formula: '介词 + 名词/代词/动名词', explanation: '【定义】\n介词和它后面的宾语合起来构成介词短语。\n介词后面跟的词叫介词宾语，可以是名词、代词宾格或动名词。\n\n【常见介词短语的句法作用】\n\n1. 作状语：表示时间、地点、方式、原因等\n   - 时间状语：in the morning, on Sunday, at night\n   - 地点状语：at home, in the classroom, on the wall\n   - 方式状语：by bus, with a pen, in English\n   - 原因状语：because of the rain, for this reason\n\n2. 作定语：修饰名词（放在被修饰的名词后面）\n   - the book on the desk 书桌上的书\n   - the girl in red 穿红衣服的女孩\n   - a map of China 一张中国地图\n\n3. 作表语：放在be动词后面\n   - The book is on the desk. 书在书桌上。\n   - He is at home. 他在家。\n\n【常用介词搭配】\nlook at 看\nlisten to 听\nwait for 等待\narrive at/in 到达\nbe good at 擅长\nbe interested in 对...感兴趣\ndepend on 依靠\nbe afraid of 害怕' },
    { chapter: '下册 语法', name: '反身代词', formula: 'myself, yourself, himself, herself, itself', explanation: '【定义】\n表示"我自己、你自己、他自己"等的代词叫做反身代词。\n\n【列表】\n- 第一人称单数：myself 我自己\n- 第二人称单数：yourself 你自己\n- 第三人称单数：himself 他自己，herself 她自己，itself 它自己\n- 第一人称复数：ourselves 我们自己\n- 第二人称复数：yourselves 你们自己\n- 第三人称复数：themselves 他们/她们/它们自己\n\n【用法】\n1. 作宾语：指动作回到动作执行者本身\n   - I can look after myself. 我能照顾我自己。\n   - Please help yourself to some fruit. 请随便吃点水果。\n\n2. 作同位语：用来加强名词或代词的语气\n   - I myself did it. = I did it myself. 我亲自做的。\n   - The teacher himself will tell us. 老师会亲自告诉我们。\n\n【常见搭配】\n- enjoy oneself 玩得高兴\n- help oneself to 随便吃/用...\n- look after oneself 照顾自己\n- teach oneself 自学\n- by oneself 独自地\n- say to oneself 自言自语' },
    { chapter: '下册 语法', name: '情态动词should', formula: 'should + 动词原形，表应该', explanation: '【定义】\nshould是情态动词，表示"应该、应当"，表示建议、劝告、义务或责任。\n\n【用法】\n1. 表示劝告、建议（应该）\n   - You should study hard. 你应该努力学习。\n   - We should help each other. 我们应该互相帮助。\n\n2. 表示义务、责任（应当）\n   - You should finish your homework on time. 你应该按时完成作业。\n\n3. 表示推测（应该）\n   - They should be there by now. 他们现在应该到那里了。\n\n【结构】\n肯定句：主语 + should + 动词原形\n否定句：主语 + should not (shouldn\'t) + 动词原形\n一般疑问句：Should + 主语 + 动词原形？\n\n【例句】\n- Should I go there now? 我应该现在去那里吗？\n  Yes, you should. / No, you shouldn\'t.\n- You shouldn\'t watch TV too much. 你不应该看太多电视。\n\n【注意】\n1. should没有人称和数的变化\n2. 后面跟动词原形\n3. 是shall的过去式，但表示建议时不表过去' },
    { chapter: '下册 语法', name: '宾语从句基础', formula: '主句 + 引导词 + 主语 + 谓语', explanation: '【定义】\n在句子中作宾语的从句叫做宾语从句。\n\n【三种类型】\n\n1. 由that引导（that在口语中常省略）\n   - I know (that) you are right. 我知道你是对的。\n   - He says (that) he will come tomorrow. 他说他明天会来。\n\n2. 由if/whether引导（是否）\n   - I don\'t know if/whether he will come. 我不知道他是否会来。\n   - Can you tell me if it will rain tomorrow? 你能告诉我明天是否会下雨吗？\n\n3. 由特殊疑问词引导\n   - Do you know where he lives? 你知道他住在哪里吗？\n   - Please tell me what your name is. 请告诉我你叫什么名字。\n\n【注意事项】\n1. 宾语从句用陈述语序（引导词 + 主语 + 谓语）\n2. 主句是现在时，从句时态根据实际情况而定\n3. 主句是过去时，从句要用相应的过去时态（客观真理除外）\n\n【例句】\n- I think that he is a good student. 我认为他是个好学生。\n- She asked if I liked English. 她问我是否喜欢英语。\n- We know that the earth goes around the sun. 我们知道地球绕着太阳转。（客观真理用一般现在时）' },
    { chapter: '下册 语法', name: '不定式to do', formula: 'want to do, like to do, decide to do', explanation: '【定义】\n"to + 动词原形"构成的结构叫做动词不定式（to do）。to是不定式符号，没有词义。\n\n【基本形式】\n肯定式：to do\n否定式：not to do\n\n【用法】\n1. 作宾语：某些动词后面要求用不定式作宾语\n   - want to do 想要做\n   - would like to do 想要做\n   - decide to do 决定做\n   - hope to do 希望做\n   - plan to do 计划做\n   - try to do 尽力做\n   - like to do 喜欢做\n   - learn to do 学习做\n\n2. 作宾语补足语\n   - ask sb. to do 叫某人做\n   - tell sb. to do 告诉某人做\n   - want sb. to do 想要某人做\n   - help sb. (to) do 帮助某人做\n\n3. 作目的状语\n   - I come here to see you. 我来这里看你。\n\n4. 作主语\n   - To learn English well is not easy. 学好英语不容易。\n   （常用it作形式主语：It is not easy to learn English well.）\n\n【注意】\n使役动词（make, let, have）和感官动词（see, hear, watch等）后面的不定式要省略to。' },
    { chapter: '下册 语法', name: '副词', formula: '修饰动词、形容词、副词或全句', explanation: '【定义】\n副词是用来修饰动词、形容词、其他副词或全句的词。\n\n【用法】\n1. 修饰动词：run fast 跑得快\n2. 修饰形容词：very good 非常好\n3. 修饰副词：very fast 非常快\n4. 修饰整个句子：Luckily, I passed the exam. 幸运的是，我通过了考试。\n\n【构成】\n1. 形容词 + ly → 副词\n   - quick → quickly 快地\n   - slow → slowly 慢地\n   - careful → carefully 仔细地\n   - happy → happily 高兴地\n\n2. 形容词和副词同形\n   - fast adj. 快的 / adv. 快地\n   - early adj. 早的 / adv. 早地\n   - late adj. 晚的 / adv. 晚地\n   - hard adj. 困难的 / adv. 努力地\n\n3. 不规则变化\n   - good → well 好地\n   - bad → badly 坏地\n\n【分类】\n1. 时间副词：now, then, yesterday, tomorrow, soon\n2. 地点副词：here, there, home, upstairs\n3. 方式副词：quickly, carefully, happily\n4. 程度副词：very, quite, too, much, so\n5. 频率副词：always, usually, often, sometimes, never' },
    { chapter: '下册 语法', name: '被动语态基础', formula: 'be + 动词过去分词', explanation: '【被动语态】\n\n【定义】\n被动语态表示主语是动作的承受者（即动作的对象）。\n主动语态：主语发出动作 → 宾语承受动作\n被动语态：主语承受动作 → by + 动作发出者\n\n【基本结构】\nbe + 及物动词的过去分词\n\n【各时态的被动语态】\n\n1. 一般现在时的被动：am/is/are + 过去分词\n   - English is spoken in many countries. 许多国家说英语。\n   - The book is written by Lu Xun. 这本书是鲁迅写的。\n\n2. 一般过去时的被动：was/were + 过去分词\n   - The bridge was built in 1990. 这座桥建于1990年。\n   - The letter was written yesterday. 这封信是昨天写的。\n\n3. 一般将来时的被动：will be + 过去分词\n   - The work will be finished tomorrow. 这项工作明天将完成。\n\n【主动变被动的方法】\n1. 宾语变主语\n2. 谓语变被动（be + 过去分词，时态不变）\n3. 主语变by的宾语（可省略）\n\n例句：\n主动：We planted many trees. 我们种了许多树。\n被动：Many trees were planted (by us). 许多树被（我们）种了。' },
    { chapter: '下册 语法', name: '并列句', formula: '用and, but, or等连词连接两个独立句子', explanation: '【并列句定义】\n由两个或两个以上的简单句并列连接起来的句子叫并列句。\n简单句之间用并列连词连接。\n\n【常见并列连词】\n\n1. 表示并列、递进关系\n   - and 和，并且\n   - both...and... 两者都\n   - not only...but also... 不但...而且...\n   - as well as 也，以及\n   例句：I like English and he likes math. 我喜欢英语，他喜欢数学。\n\n2. 表示转折关系\n   - but 但是\n   - however 然而\n   - yet 然而\n   - while 而，却\n   例句：He is young, but he knows a lot. 他很年轻，但知道很多。\n\n3. 表示选择关系\n   - or 或者，否则\n   - either...or... 要么...要么...\n   - neither...nor... 既不...也不...\n   例句：Hurry up, or you\'ll be late. 快点，否则你会迟到的。\n\n4. 表示因果关系\n   - so 所以\n   - for 因为\n   - therefore 因此\n   例句：It was late, so I went home. 天晚了，所以我回家了。' },
    { chapter: '下册 语法', name: '感叹句', formula: 'What + 名词! / How + 形容词/副词!', explanation: '【感叹句定义】\n用来表示喜、怒、哀、乐等强烈感情的句子叫感叹句。\n一般用what或how引导，句末用感叹号。\n\n【what引导的感叹句】\nwhat修饰名词或名词短语。\n\n1. What + a/an + 形容词 + 单数可数名词 + 主语 + 谓语！\n   What a beautiful girl (she is)! 她是个多漂亮的女孩啊！\n\n2. What + 形容词 + 复数可数名词 + 主语 + 谓语！\n   What interesting books (they are)! 多有趣的书啊！\n\n3. What + 形容词 + 不可数名词 + 主语 + 谓语！\n   What fine weather (it is)! 多好的天气啊！\n\n【how引导的感叹句】\nhow修饰形容词、副词或句子。\n\n1. How + 形容词/副词 + 主语 + 谓语！\n   How beautiful the girl is! 这女孩多漂亮啊！\n   How fast he runs! 他跑得多快啊！\n\n2. How + 主语 + 谓语！\n   How time flies! 时间过得真快！\n\n【判断用what还是how】\n看句末的主语和谓语之前最后一个词：\n- 是名词用what\n- 是形容词/副词用how' },
    { chapter: '下册 语法', name: '反意疑问句', formula: '前肯后否，前否后肯', explanation: '【反意疑问句定义】\n附在陈述句后面，对陈述句所说的事实提出疑问的句子，叫反意疑问句。\n表示说话人对事物有一定看法，但需要对方证实。\n\n【结构】\n陈述句 + 简短问句\n前肯后否，前否后肯。\n\n【基本规则】\n1. 前肯后否：\n   He is a student, isn\'t he? 他是学生，对吗？\n   They like music, don\'t they? 他们喜欢音乐，不是吗？\n\n2. 前否后肯：\n   He isn\'t a student, is he? 他不是学生，对吗？\n   They don\'t like music, do they? 他们不喜欢音乐，是吗？\n\n【回答】\n根据事实回答，事实是肯定的用Yes，事实是否定的用No。\n- He is a student, isn\'t he? 他是学生，对吗？\n  Yes, he is. 是的，他是。/ No, he isn\'t. 不，他不是。\n\n【特殊情况】\n1. 陈述部分有never, few, little, hardly等否定词时，疑问部分用肯定式\n   He never smokes, does he? 他从不抽烟，对吗？\n\n2. There be句型的反意疑问句用be there\n   There is a book on the desk, isn\'t there? 书桌上有本书，对吗？' },
];

const g1EnglishVocabUpper = [
    { chapter: '上册 Unit 1', name: 'Unit 1 核心词汇', formula: 'hello, hi, good, morning, afternoon, evening, night, goodbye, bye, see, you, I, me, my, your, he, she, it, we, they, name, is, am, are, from, old, how, what, where, who', explanation: '【Unit 1 核心词汇表】\n\n【问候类】\n1. hello 你好\n2. hi 嗨\n3. good 好的\n4. morning 早晨，上午\n5. afternoon 下午\n6. evening 晚上，傍晚\n7. night 夜晚\n8. goodbye 再见\n9. bye 再见\n10. see 看见\n\n【人称代词】\n11. I 我（主格）\n12. me 我（宾格）\n13. my 我的\n14. your 你的，你们的\n15. he 他\n16. she 她\n17. it 它\n18. we 我们\n19. they 他们，她们，它们\n\n【be动词】\n20. am 是（用于I）\n21. is 是（用于单数）\n22. are 是（用于复数和you）\n\n【疑问词】\n23. what 什么\n24. how 怎样\n25. where 在哪里\n26. who 谁\n\n【其他】\n27. name 名字\n28. from 从，来自\n29. old 老的，...岁的\n30. you 你，你们' },
    { chapter: '上册 Unit 2', name: 'Unit 2 核心词汇', formula: 'family, father, mother, brother, sister, parent, grandfather, grandmother, this, that, these, those', explanation: '【Unit 2 核心词汇表】\n\n【家庭成员】\n1. family 家庭\n2. father 父亲，爸爸\n3. mother 母亲，妈妈\n4. dad 爸爸（口语）\n5. mom 妈妈（口语）\n6. parent 父亲或母亲\n7. parents 父母\n8. brother 兄，弟\n9. sister 姐，妹\n10. grandfather 祖父，外祖父\n11. grandmother 祖母，外祖母\n12. grandpa 爷爷，外公（口语）\n13. grandma 奶奶，外婆（口语）\n14. grandparent 祖父/祖母/外祖父/外祖母\n15. grandparents 祖父母，外祖父母\n16. uncle 叔叔，舅舅，伯父，姑父，姨父\n17. aunt 阿姨，姑姑，婶婶，舅妈，姨妈\n18. cousin 堂（表）兄弟，堂（表）姐妹\n19. son 儿子\n20. daughter 女儿\n\n【指示代词】\n21. this 这，这个\n22. that 那，那个\n23. these 这些\n24. those 那些\n\n【其他】\n25. photo 照片\n26. picture 图片，照片\n27. of 属于，关于\n28. my 我的\n29. your 你的\n30. here 这里' },
    { chapter: '上册 Unit 3', name: 'Unit 3 核心词汇', formula: 'schoolbag, book, pen, pencil, ruler, eraser, desk, chair, where, in, on, under', explanation: '【Unit 3 核心词汇表】\n\n【学习用品】\n1. schoolbag 书包\n2. book 书\n3. pen 钢笔\n4. pencil 铅笔\n5. ruler 尺子\n6. eraser 橡皮\n7. pencil box 铅笔盒\n8. dictionary 字典，词典\n9. notebook 笔记本\n10. crayon 蜡笔\n\n【家具物品】\n11. desk 书桌\n12. chair 椅子\n13. table 桌子\n14. bed 床\n15. sofa 沙发\n16. shelf 架子\n17. box 盒子，箱子\n18. key 钥匙\n19. bag 包\n20. clock 时钟\n\n【方位介词】\n21. in 在...里面\n22. on 在...上面\n23. under 在...下面\n24. behind 在...后面\n25. near 在...附近\n26. next to 紧挨着\n27. between 在...之间\n28. in front of 在...前面\n\n【疑问词】\n29. where 在哪里\n30. what 什么' },
    { chapter: '上册 Unit 4', name: 'Unit 4 核心词汇', formula: 'get up, breakfast, lunch, dinner, go to school, have class, homework, watch TV, go to bed', explanation: '【Unit 4 核心词汇表】\n\n【日常活动】\n1. get up 起床\n2. eat breakfast 吃早饭\n3. have breakfast 吃早饭\n4. go to school 去上学\n5. go home 回家\n6. go to bed 上床睡觉\n7. have class / have lessons 上课\n8. do homework 做作业\n9. watch TV 看电视\n10. read a book 读书\n11. play sports 做运动\n12. play football 踢足球\n13. play basketball 打篮球\n14. listen to music 听音乐\n15. eat / have 吃\n\n【三餐】\n16. breakfast 早餐\n17. lunch 午餐\n18. dinner 晚餐，正餐\n19. meal 一餐\n20. food 食物\n\n【时间】\n21. morning 早上，上午\n22. afternoon 下午\n23. evening 晚上\n24. night 夜晚\n25. today 今天\n26. tomorrow 明天\n27. usually 通常\n28. often 经常\n29. sometimes 有时\n30. always 总是' },
    { chapter: '上册 Unit 5', name: 'Unit 5 核心词汇', formula: 'rice, bread, meat, fish, chicken, vegetable, fruit, water, milk, juice, tea, apple, banana', explanation: '【Unit 5 核心词汇表】\n\n【主食类】\n1. rice 米饭\n2. bread 面包\n3. noodle 面条\n4. dumpling 饺子\n5. hamburger 汉堡包\n6. sandwich 三明治\n\n【肉蛋类】\n7. meat 肉\n8. beef 牛肉\n9. pork 猪肉\n10. chicken 鸡肉\n11. fish 鱼肉\n12. egg 鸡蛋\n\n【蔬菜水果】\n13. vegetable 蔬菜\n14. tomato 西红柿\n15. potato 土豆，马铃薯\n16. carrot 胡萝卜\n17. fruit 水果\n18. apple 苹果\n19. banana 香蕉\n20. orange 橙子\n21. grape 葡萄\n22. pear 梨\n23. strawberry 草莓\n\n【饮料】\n24. water 水\n25. milk 牛奶\n26. juice 果汁\n27. tea 茶\n28. coffee 咖啡\n29. coke 可乐\n\n【其他】\n30. like 喜欢' },
    { chapter: '上册 Unit 6', name: 'Unit 6 核心词汇', formula: 'shirt, T-shirt, sweater, jacket, coat, pants, shoes, socks, hat, dress, skirt, red, blue, green', explanation: '【Unit 6 核心词汇表】\n\n【服装类】\n1. shirt 衬衫\n2. T-shirt T恤衫\n3. sweater 毛衣\n4. jacket 夹克衫\n5. coat 外套，大衣\n6. dress 连衣裙\n7. skirt 短裙\n8. pants / trousers 裤子\n9. jeans 牛仔裤\n10. shorts 短裤\n11. shoes 鞋\n12. socks 袜子\n13. hat 帽子（有边的）\n14. cap 鸭舌帽\n15. scarf 围巾\n16. gloves 手套\n\n【颜色类】\n17. red 红色（的）\n18. blue 蓝色（的）\n19. green 绿色（的）\n20. yellow 黄色（的）\n21. black 黑色（的）\n22. white 白色（的）\n23. purple 紫色（的）\n24. pink 粉色（的）\n25. orange 橙色（的）\n26. brown 棕色（的）\n27. gray / grey 灰色（的）\n\n【形容词】\n28. big 大的\n29. small 小的\n30. long 长的\n31. short 短的，矮的\n32. new 新的\n33. old 旧的，老的\n\n【其他】\n34. wear 穿，戴\n35. want 想要\n36. buy 买\n37. sell 卖\n38. price 价格\n39. cheap 便宜的\n40. expensive 昂贵的' },
    { chapter: '上册 Unit 7', name: 'Unit 7 核心词汇', formula: 'time, clock, hour, minute, day, week, month, year, Monday, Sunday, January, December', explanation: '【Unit 7 核心词汇表】\n\n【时间单位】\n1. time 时间\n2. clock 时钟\n3. hour 小时\n4. minute 分钟\n5. second 秒\n6. day 天，日\n7. week 星期，周\n8. month 月\n9. year 年\n\n【星期】\n10. Monday 星期一\n11. Tuesday 星期二\n12. Wednesday 星期三\n13. Thursday 星期四\n14. Friday 星期五\n15. Saturday 星期六\n16. Sunday 星期日\n17. weekday 工作日\n18. weekend 周末\n\n【月份】\n19. January 一月\n20. February 二月\n21. March 三月\n22. April 四月\n23. May 五月\n24. June 六月\n25. July 七月\n26. August 八月\n27. September 九月\n28. October 十月\n29. November 十一月\n30. December 十二月\n\n【其他】\n31. today 今天\n32. tomorrow 明天\n33. yesterday 昨天\n34. morning 早上\n35. afternoon 下午\n36. evening 晚上\n37. night 夜晚\n38. noon 中午\n39. o\'clock 点钟\n40. half 一半' },
    { chapter: '上册 Unit 8', name: 'Unit 8 核心词汇', formula: 'sunny, rainy, cloudy, windy, snowy, hot, cold, warm, cool, weather', explanation: '【Unit 8 核心词汇表】\n\n【天气形容词】\n1. sunny 晴朗的\n2. rainy 下雨的，多雨的\n3. cloudy 多云的，阴天的\n4. windy 有风的，多风的\n5. snowy 下雪的，多雪的\n6. foggy 有雾的\n\n【天气名词/动词】\n7. sun 太阳，阳光\n8. rain 雨，下雨\n9. cloud 云\n10. wind 风\n11. snow 雪，下雪\n12. fog 雾\n\n【温度描述】\n13. hot 热的\n14. cold 冷的\n15. warm 温暖的\n16. cool 凉爽的\n17. cool 凉快的\n18. temperature 温度\n\n【天气相关】\n19. weather 天气\n20. sky 天空\n21. sun 太阳\n22. moon 月亮\n23. star 星星\n24. rainbow 彩虹\n25. storm 暴风雨\n26. thunder 雷\n27. lightning 闪电\n28. ice 冰\n29. season 季节\n30. spring 春天\n31. summer 夏天\n32. autumn / fall 秋天\n33. winter 冬天\n\n【动词】\n34. shine 照耀\n35. blow 吹\n36. rain 下雨\n37. snow 下雪\n38. become 变得\n39. report 报告\n40. forecast 预报' },
    { chapter: '上册 Unit 9', name: 'Unit 9 核心词汇', formula: 'English, math, Chinese, PE, music, art, science, teacher, student, classroom, playground, library', explanation: '【Unit 9 核心词汇表】\n\n【课程科目】\n1. English 英语\n2. math / maths 数学\n3. Chinese 语文，汉语\n4. PE / physical education 体育\n5. music 音乐\n6. art 美术，艺术\n7. science 科学\n8. history 历史\n9. geography 地理\n10. biology 生物\n11. politics 政治\n12. computer 计算机\n\n【学校人员】\n13. teacher 老师\n14. student 学生\n15. classmate 同学\n16. headmaster 校长\n17. monitor 班长\n\n【学校场所】\n18. classroom 教室\n19. playground 操场\n20. library 图书馆\n21. lab / laboratory 实验室\n22. canteen 食堂\n23. dining hall 食堂\n24. teachers\' office 教师办公室\n25. gym 体育馆\n26. garden 花园\n27. hallway 走廊\n28. toilet 厕所\n29. office 办公室\n\n【学习活动】\n30. study 学习\n31. learn 学习\n32. read 读，阅读\n33. write 写\n34. listen 听\n35. speak 说\n36. recite 背诵\n37. practice 练习\n38. exam 考试\n39. test 测验\n40. homework 作业' },
    { chapter: '上册 语法词汇1', name: '语法词汇1：词类', formula: '名词、动词、形容词、副词、代词、数词、介词、冠词、连词、感叹词', explanation: '【英语词类（十大词类）】\n\n1. 名词 (n. / noun)\n   表示人、事物、地点或抽象概念的名称\n   例：book, teacher, China, love\n\n2. 动词 (v. / verb)\n   表示动作或状态\n   例：run, eat, is, have, can\n\n3. 形容词 (adj. / adjective)\n   修饰名词，表示人或事物的特征\n   例：big, red, happy, good\n\n4. 副词 (adv. / adverb)\n   修饰动词、形容词或其他副词\n   例：fast, very, quickly, now\n\n5. 代词 (pron. / pronoun)\n   代替名词或起名词作用\n   例：I, you, he, this, who, my\n\n6. 数词 (num. / numeral)\n   表示数量或顺序\n   例：one, two, first, second\n\n7. 介词 (prep. / preposition)\n   用在名词、代词前，表示与其他词的关系\n   例：in, on, at, for, with\n\n8. 冠词 (art. / article)\n   用在名词前，帮助说明名词的含义\n   例：a, an, the\n\n9. 连词 (conj. / conjunction)\n   连接词与词、短语与短语或句子与句子\n   例：and, but, because, if\n\n10. 感叹词 (interj. / interjection)\n    表示说话时的感情或口气\n    例：oh, hello, ah, well' },
    { chapter: '上册 语法词汇2', name: '语法词汇2：时态', formula: '一般现在时、现在进行时、一般将来时、一般过去时', explanation: '【英语八大时态（初一常见四种）】\n\n1. 一般现在时\n   表示经常性、习惯性的动作或存在的状态\n   构成：主语 + 动词原形 / 三单形式\n   标志词：always, usually, often, every day\n   例：I get up at 6 every day. 我每天6点起床。\n\n2. 现在进行时\n   表示现在正在进行的动作\n   构成：主语 + am/is/are + 动词ing\n   标志词：now, look, listen, at the moment\n   例：He is reading a book now. 他现在正在读书。\n\n3. 一般将来时\n   表示将来要发生的动作或存在的状态\n   构成：will + 动词原形 / be going to + 动词原形\n   标志词：tomorrow, next week, soon, in the future\n   例：I will go to Beijing tomorrow. 我明天要去北京。\n\n4. 一般过去时\n   表示过去某个时间发生的动作或状态\n   构成：主语 + 动词过去式\n   标志词：yesterday, last week, ago, just now\n   例：I went to park yesterday. 我昨天去了公园。\n\n【其他时态（了解）】\n5. 过去进行时\n6. 现在完成时\n7. 过去完成时\n8. 过去将来时' },
    { chapter: '上册 语法词汇3', name: '语法词汇3：句子成分', formula: '主语、谓语、宾语、表语、定语、状语、补语', explanation: '【句子成分】\n\n1. 主语 (subject)\n   句子所说的人或事物，句子的主体\n   一般在句首，由名词、代词、数词等充当\n   例：The students are studying.（The students是主语）\n\n2. 谓语 (predicate)\n   说明主语的动作或状态\n   由动词充当\n   例：He runs fast.（runs是谓语）\n\n3. 宾语 (object)\n   动作的承受者或对象\n   放在及物动词或介词后面\n   例：I like English.（English是宾语）\n\n4. 表语 (predicative)\n   放在系动词后面，说明主语的性质、状态、身份等\n   系动词：be, look, sound, smell, taste, feel, become等\n   例：She is happy.（happy是表语）\n\n5. 定语 (attribute)\n   修饰名词或代词\n   形容词、名词、代词等都可以作定语\n   例：a red apple（red是定语，修饰apple）\n\n6. 状语 (adverbial)\n   修饰动词、形容词、副词或整个句子\n   表示时间、地点、方式、程度、原因等\n   例：He runs fast.（fast是方式状语）\n\n7. 补语 (complement)\n   补充说明宾语或主语\n   例：We call him Jack.（Jack是宾语补足语）' },
    { chapter: '上册 语法词汇4', name: '语法词汇4：简单句五种基本句型', formula: '主谓、主谓宾、主系表、主谓双宾、主谓宾宾补', explanation: '【简单句五种基本句型】\n\n1. 主语 + 不及物动词 (S + V)\n   主语 + 谓语（不及物动词不能加宾语）\n   例：The sun rises. 太阳升起。\n   例：He runs fast. 他跑得快。\n\n2. 主语 + 及物动词 + 宾语 (S + V + O)\n   主语 + 谓语 + 宾语\n   例：I like music. 我喜欢音乐。\n   例：She reads English every day. 她每天读英语。\n\n3. 主语 + 系动词 + 表语 (S + V + P)\n   主语 + 系动词 + 表语\n   例：He is a student. 他是一名学生。\n   例：The flowers look beautiful. 花看起来很美。\n\n4. 主语 + 及物动词 + 间接宾语 + 直接宾语 (S + V + IO + DO)\n   双宾语结构：人（间宾）+ 物（直宾）\n   例：She gave me a book. 她给了我一本书。\n   例：My father bought me a bike. 我爸爸给我买了一辆自行车。\n\n5. 主语 + 及物动词 + 宾语 + 宾语补足语 (S + V + O + OC)\n   主谓宾宾补结构\n   例：We call him Tom. 我们叫他汤姆。\n   例：The teacher asked me to clean the classroom. 老师让我打扫教室。\n\n【There be句型】\n表示"某地有某物"：There is a book on the desk.' },
    { chapter: '上册 短语1', name: '短语1：动词短语', formula: 'get up, go to school, watch TV, do homework, look at, listen to', explanation: '【上册常见动词短语】\n\n【日常活动】\n1. get up 起床\n2. go to school 去上学\n3. go home 回家\n4. go to bed 睡觉\n5. eat breakfast 吃早饭\n6. have lunch 吃午饭\n7. have dinner 吃晚饭\n8. do homework 做作业\n9. watch TV 看电视\n10. read books 读书\n11. play sports 做运动\n12. play football 踢足球\n13. play basketball 打篮球\n14. play games 玩游戏\n15. listen to music 听音乐\n\n【look短语】\n16. look at 看...\n17. look for 寻找\n18. look after 照顾\n19. look like 看起来像\n20. look up 查阅（字典）\n\n【其他动词短语】\n21. listen to 听...\n22. talk about 谈论\n23. talk with 和...交谈\n24. think about 考虑\n25. think of 想起，认为\n26. wait for 等待\n27. come from 来自\n28. be from 来自\n29. help...with... 在...方面帮助...\n30. learn from 向...学习' },
    { chapter: '上册 短语2', name: '短语2：介词短语', formula: 'at home, at school, in the morning, on foot, by bus, in English', explanation: '【上册常见介词短语】\n\n【地点类】\n1. at home 在家\n2. at school 在学校\n3. at work 在工作\n4. in the classroom 在教室里\n5. on the desk 在书桌上\n6. under the bed 在床下\n7. near the door 在门附近\n8. next to the window 紧挨着窗户\n9. in front of the house 在房子前面\n10. behind the tree 在树后面\n\n【时间类】\n11. in the morning 在早上\n12. in the afternoon 在下午\n13. in the evening 在晚上\n14. at noon 在中午\n15. at night 在夜晚\n16. on Monday 在星期一\n17. on Sunday morning 在星期天早上\n18. at 7 o\'clock 在7点钟\n19. in spring 在春天\n20. in June 在六月\n21. in 2024 在2024年\n\n【方式类】\n22. on foot 步行\n23. by bus 乘公共汽车\n24. by bike 骑自行车\n25. by car 乘小汽车\n26. by train 乘火车\n27. by plane / by air 乘飞机\n28. in English 用英语\n29. in Chinese 用汉语\n30. with a pen 用钢笔' },
];

const g1EnglishVocabLower = [
    { chapter: '下册 Unit 1', name: 'Unit 1 核心词汇', formula: 'ask, tell, way, go straight, turn left, turn right, bus, bike, foot, walk', explanation: '【Unit 1 核心词汇表】\n\n【交通方式】\n1. bus 公共汽车\n2. car 小汽车\n3. bike / bicycle 自行车\n4. train 火车\n5. plane 飞机\n6. ship 船\n7. subway 地铁\n8. taxi 出租车\n9. foot 脚（on foot 步行）\n10. walk 走路，步行\n\n【方向与指路】\n11. way 路，方式，方法\n12. go straight 直走\n13. turn left 向左转\n14. turn right 向右转\n15. crossing 十字路口\n16. corner 角落，拐角\n17. along 沿着\n18. across 穿过，横过\n19. past 经过\n20. between 在...之间\n\n【问路用语】\n21. ask 问\n22. tell 告诉\n23. excuse me 打扰一下\n24. where 在哪里\n25. how 怎样\n26. which 哪一个\n27. get to 到达\n28. find 找到\n29. miss 错过，想念\n30. thank 感谢\n31. thanks 谢谢\n\n【地点】\n32. station 车站\n33. stop 停车站\n34. airport 机场\n35. hospital 医院\n36. hotel 旅馆\n37. museum 博物馆\n38. park 公园\n39. zoo 动物园\n40. library 图书馆' },
    { chapter: '下册 Unit 2', name: 'Unit 2 核心词汇', formula: 'weekend, visit, shopping, cinema, movie, sport, swim, clean, wash, tomorrow', explanation: '【Unit 2 核心词汇表】\n\n【周末活动】\n1. weekend 周末\n2. weekday 工作日\n3. Saturday 星期六\n4. Sunday 星期日\n5. visit 参观，拜访\n6. go shopping 去购物\n7. go swimming 去游泳\n8. go to the cinema 去看电影\n9. see a movie 看电影\n10. watch a movie 看电影\n11. play sports 做运动\n12. have a good time 玩得高兴\n13. enjoy oneself 玩得高兴\n14. have fun 玩得开心\n15. clean the room 打扫房间\n16. wash clothes 洗衣服\n17. do some washing 洗衣服\n18. do some cleaning 打扫卫生\n19. listen to music 听音乐\n20. draw pictures 画画\n\n【拜访人物】\n21. grandparent 祖父/母\n22. grandpa 爷爷\n23. grandma 奶奶\n24. friend 朋友\n25. relative 亲戚\n\n【时间】\n26. tomorrow 明天\n27. today 今天\n28. yesterday 昨天\n29. last week 上周\n30. next week 下周\n31. this morning 今天早上\n32. this afternoon 今天下午\n33. this evening 今天晚上\n34. soon 不久\n35. later 后来\n\n【动词】\n36. will 将要\n37. going to 打算\n38. plan 计划\n39. decide 决定\n40. invite 邀请' },
    { chapter: '下册 Unit 3', name: 'Unit 3 核心词汇', formula: 'panda, tiger, lion, elephant, monkey, bear, rabbit, bird, fish, snake, big, small, long, short, tall', explanation: '【Unit 3 核心词汇表】\n\n【常见动物】\n1. panda 熊猫\n2. tiger 老虎\n3. lion 狮子\n4. elephant 大象\n5. monkey 猴子\n6. bear 熊\n7. wolf 狼\n8. fox 狐狸\n9. rabbit 兔子\n10. deer 鹿\n11. horse 马\n12. cow 奶牛\n13. sheep 绵羊\n14. pig 猪\n15. dog 狗\n16. cat 猫\n17. mouse 老鼠\n\n【鸟类】\n18. bird 鸟\n19. eagle 鹰\n20. parrot 鹦鹉\n21. chicken 鸡\n22. duck 鸭\n23. goose 鹅\n\n【其他动物】\n24. fish 鱼\n25. snake 蛇\n26. frog 青蛙\n27. turtle 乌龟\n28. butterfly 蝴蝶\n29. bee 蜜蜂\n30. ant 蚂蚁\n\n【动物特征】\n31. strong 强壮的\n32. weak 虚弱的\n33. fast 快的\n34. slow 慢的\n35. big 大的\n36. small 小的\n37. long 长的\n38. short 短的\n39. tall 高的\n40. smart 聪明的\n41. cute 可爱的\n42. dangerous 危险的\n43. friendly 友好的\n44. shy 害羞的\n45. heavy 重的' },
    { chapter: '下册 Unit 4', name: 'Unit 4 核心词汇', formula: 'teacher, doctor, nurse, worker, farmer, driver, cook, policeman, engineer, scientist', explanation: '【Unit 4 核心词汇表】\n\n【常见职业】\n1. teacher 教师，老师\n2. doctor 医生\n3. nurse 护士\n4. worker 工人\n5. farmer 农民\n6. driver 司机\n7. cook 厨师\n8. policeman 警察\n9. policewoman 女警察\n10. soldier 士兵\n11. engineer 工程师\n12. scientist 科学家\n13. singer 歌手\n14. dancer 舞蹈家\n15. writer 作家，作者\n16. artist 艺术家，画家\n17. actor 演员（男）\n18. actress 演员（女）\n19. doctor 医生\n20. dentist 牙医\n21. lawyer 律师\n22. reporter 记者\n23. businessman 商人\n24. astronaut 宇航员\n25. pilot 飞行员\n26. waiter 服务员（男）\n27. waitress 服务员（女）\n28. manager 经理\n29. secretary 秘书\n30. student 学生\n\n【工作单位】\n31. school 学校\n32. hospital 医院\n33. factory 工厂\n34. farm 农场\n35. restaurant 餐馆\n36. company 公司\n37. office 办公室\n38. bank 银行\n39. police station 警察局\n40. lab / laboratory 实验室\n\n【工作相关】\n41. work 工作\n42. job 工作\n43. career 职业\n44. salary 工资\n45. hard 努力地' },
    { chapter: '下册 Unit 5', name: 'Unit 5 核心词汇', formula: 'birthday, cake, gift, party, candle, celebrate, wish, Spring Festival, Christmas, Children\'s Day', explanation: '【Unit 5 核心词汇表】\n\n【生日相关】\n1. birthday 生日\n2. birthday cake 生日蛋糕\n3. gift 礼物\n4. present 礼物\n5. birthday party 生日派对\n6. candle 蜡烛\n7. wish 愿望，希望\n8. blow 吹\n9. blow out 吹灭\n10. celebrate 庆祝\n11. celebration 庆祝活动\n12. birthday card 生日卡片\n13. birthday song 生日歌\n14. invite 邀请\n15. happy birthday 生日快乐\n\n【中国节日】\n16. Spring Festival 春节\n17. Lantern Festival 元宵节\n18. Dragon Boat Festival 端午节\n19. Mid-Autumn Festival 中秋节\n20. National Day 国庆节\n21. New Year\'s Day 元旦\n22. Labor Day / May Day 劳动节\n23. Children\'s Day 儿童节\n24. Teachers\' Day 教师节\n25. Tree Planting Day 植树节\n\n【西方节日】\n26. Christmas 圣诞节\n27. Halloween 万圣节\n28. Thanksgiving Day 感恩节\n29. Easter 复活节\n30. Valentine\'s Day 情人节\n31. April Fool\'s Day 愚人节\n32. Mother\'s Day 母亲节\n33. Father\'s Day 父亲节\n\n【节日活动】\n34. have a party 举办派对\n35. give gifts 送礼物\n36. get together 团聚\n37. have a big dinner 吃大餐\n38. watch fireworks 看烟花\n39. lucky money 压岁钱\n40. best wishes 最美好的祝愿' },
    { chapter: '下册 Unit 6', name: 'Unit 6 核心词汇', formula: 'tall, short, fat, thin, strong, hair, eye, face, kind, friendly, shy, outgoing', explanation: '【Unit 6 核心词汇表】\n\n【外貌描述】\n1. tall 高的\n2. short 矮的，短的\n3. fat 胖的\n4. thin 瘦的\n5. heavy 重的\n6. slim 苗条的\n7. strong 强壮的\n8. weak 虚弱的\n9. of medium height 中等身高\n10. of medium build 中等体型\n\n【头部五官】\n11. hair 头发\n12. straight hair 直发\n13. curly hair 卷发\n14. long hair 长头发\n15. short hair 短头发\n16. black hair 黑头发\n17. eye 眼睛\n18. big eyes 大眼睛\n19. small eyes 小眼睛\n20. nose 鼻子\n21. mouth 嘴\n22. face 脸\n23. round face 圆脸\n24. long face 长脸\n25. ear 耳朵\n26. tooth / teeth 牙齿\n\n【性格描述】\n27. kind 善良的，和蔼的\n28. friendly 友好的\n29. shy 害羞的\n30. outgoing 外向的\n31. quiet 安静的\n32. active 活跃的\n33. clever 聪明的\n34. smart 聪明的\n35. lazy 懒惰的\n36. hard-working 勤奋的\n37. brave 勇敢的\n38. funny 有趣的，滑稽的\n39. honest 诚实的\n40. polite 有礼貌的' },
    { chapter: '下册 Unit 7', name: 'Unit 7 核心词汇', formula: 'yesterday, last, ago, just now, was, were, went, did, had, came, went, saw', explanation: '【Unit 7 核心词汇表】\n\n【过去时间状语】\n1. yesterday 昨天\n2. yesterday morning 昨天早上\n3. yesterday afternoon 昨天下午\n4. yesterday evening 昨天晚上\n5. last week 上周\n6. last month 上个月\n7. last year 去年\n8. last night 昨晚\n9. ... ago ...以前\n10. just now 刚才\n11. at that time 在那时\n12. in the past 在过去\n13. once upon a time 从前\n14. the day before yesterday 前天\n15. last Monday 上周一\n\n【常见不规则动词过去式】\n16. am / is → was 是\n17. are → were 是\n18. go → went 去\n19. do → did 做\n20. have → had 有，吃\n21. come → came 来\n22. see → saw 看见\n23. say → said 说\n24. get → got 得到\n25. make → made 制作\n26. eat → ate 吃\n27. drink → drank 喝\n28. buy → bought 买\n29. take → took 拿走\n30. give → gave 给\n31. run → ran 跑\n32. swim → swam 游泳\n33. sing → sang 唱歌\n34. sit → sat 坐\n35. stand → stood 站\n36. sleep → slept 睡觉\n37. read → read 读\n38. write → wrote 写\n39. speak → spoke 说\n40. tell → told 告诉' },
    { chapter: '下册 Unit 8', name: 'Unit 8 核心词汇', formula: 'plan, future, tomorrow, next, will, going to, want, hope, decide, dream', explanation: '【Unit 8 核心词汇表】\n\n【计划与打算】\n1. plan 计划，打算\n2. future 未来，将来\n3. tomorrow 明天\n4. next week 下周\n5. next month 下个月\n6. next year 明年\n7. will 将要\n8. be going to 打算，将要\n9. want 想要\n10. hope 希望\n11. wish 希望，愿望\n12. decide 决定\n13. decision 决定\n14. dream 梦想，做梦\n15. goal 目标\n16. prepare 准备\n17. ready 准备好的\n18. look forward to 期待\n19. expect 期待\n20. consider 考虑\n\n【将来时间】\n21. tomorrow 明天\n22. the day after tomorrow 后天\n23. next week 下周\n24. next month 下个月\n25. next year 明年\n26. soon 不久，很快\n27. in the future 在将来\n28. later 稍后，以后\n29. one day 有一天\n30. some day 某一天\n\n【动词短语】\n31. plan to do 计划做\n32. want to do 想要做\n33. hope to do 希望做\n34. wish to do 希望做\n35. decide to do 决定做\n36. would like to do 想要做\n37. be going to do 打算做\n38. will do 将要做\n39. prepare for 为...做准备\n40. dream of 梦想' },
    { chapter: '下册 语法词汇1', name: '语法词汇1：比较级和最高级', formula: '比较级：加er/加more；最高级：加est/加most', explanation: '【比较级和最高级规则变化】\n\n1. 一般单音节词：加er / est\n   tall → taller → tallest\n   long → longer → longest\n   small → smaller → smallest\n\n2. 以不发音的e结尾：加r / st\n   nice → nicer → nicest\n   large → larger → largest\n   late → later → latest\n\n3. 以辅音字母+y结尾：变y为i加er / est\n   happy → happier → happiest\n   easy → easier → easiest\n   heavy → heavier → heaviest\n\n4. 重读闭音节（辅元辅）：双写最后字母加er / est\n   big → bigger → biggest\n   hot → hotter → hottest\n   thin → thinner → thinnest\n   fat → fatter → fattest\n\n5. 多音节词和部分双音节词：加more / most\n   beautiful → more beautiful → most beautiful\n   interesting → more interesting → most interesting\n   important → more important → most important\n\n【不规则变化】\n1. good / well → better → best\n2. bad / badly / ill → worse → worst\n3. many / much → more → most\n4. little → less → least\n5. far → farther / further → farthest / furthest\n\n【常用句型】\n1. 比较级 + than 比...更...\n2. the + 最高级 + of / in... 最...的\n3. as + 原级 + as 和...一样...\n4. not as / so + 原级 + as 不如...' },
    { chapter: '下册 语法词汇2', name: '语法词汇2：被动语态', formula: 'be + 过去分词，表示"被..."', explanation: '【被动语态】\n\n【定义】\n被动语态表示主语是动作的承受者，意思是"被..."。\n\n【基本构成】\nbe + 及物动词的过去分词\n\n【各种时态的被动语态】\n\n1. 一般现在时的被动\n   am / is / are + 过去分词\n   English is spoken in many countries.\n   许多国家说英语。\n\n2. 一般过去时的被动\n   was / were + 过去分词\n   The bridge was built in 1990.\n   这座桥建于1990年。\n\n3. 一般将来时的被动\n   will be + 过去分词 / be going to be + 过去分词\n   The work will be finished tomorrow.\n   这项工作明天将完成。\n\n4. 现在进行时的被动（了解）\n   am / is / are + being + 过去分词\n\n5. 现在完成时的被动（了解）\n   have / has + been + 过去分词\n\n【被动语态的用法】\n1. 不知道或没必要指出动作的执行者\n2. 强调动作的承受者\n3. 动作的执行者是泛指或不言自明\n\n【by短语】\n如果需要指出动作的执行者，用by短语：\nThe book was written by Lu Xun.\n这本书是鲁迅写的。' },
    { chapter: '下册 语法词汇3', name: '语法词汇3：动词不定式', formula: 'to + 动词原形，作宾语、状语、宾补等', explanation: '【动词不定式】\n\n【形式】\n基本形式：to + 动词原形\n否定形式：not + to + 动词原形\n\n【用法】\n\n1. 作宾语（某些动词后面只跟不定式）\n   want to do 想要做\n   hope to do 希望做\n   decide to do 决定做\n   plan to do 计划做\n   would like to do 想要做\n   learn to do 学习做\n   try to do 尽力做\n   forget to do 忘记要做\n   remember to do 记得要做\n\n2. 作宾语补足语\n   ask sb. to do sth. 让某人做某事\n   tell sb. to do sth. 告诉某人做某事\n   want sb. to do sth. 想要某人做某事\n   invite sb. to do sth. 邀请某人做某事\n   allow sb. to do sth. 允许某人做某事\n   help sb. (to) do sth. 帮助某人做某事\n\n3. 作目的状语\n   I come here to see you. 我来这儿看你。\n\n4. 作主语\n   To learn English well is important.\n   = It is important to learn English well.\n   学好英语很重要。\n\n5. 作表语\n   My dream is to be a doctor.\n   我的梦想是成为一名医生。\n\n【省略to的情况】\n使役动词 make, let, have 和感官动词 see, hear, watch, feel, notice 等后面，不定式要省略to。' },
    { chapter: '下册 短语1', name: '短语1：动词短语（下）', formula: 'look after, look for, look like, get on, get off, turn on, turn off, take off, put on, take care of', explanation: '【下册常见动词短语】\n\n【look短语】\n1. look at 看...\n2. look for 寻找\n3. look after 照顾，照看\n4. look like 看起来像\n5. look up 查阅，查找\n6. look over 检查\n7. look around 环顾四周\n8. look forward to 期待\n\n【get短语】\n9. get up 起床\n10. get on 上车\n11. get off 下车\n12. get to 到达\n13. get back 回来\n14. get ready 准备好\n15. get on well with 和...相处得好\n\n【turn短语】\n16. turn on 打开（电器）\n17. turn off 关掉（电器）\n18. turn up 调大（音量）\n19. turn down 调小（音量）\n20. turn left 向左转\n21. turn right 向右转\n\n【put短语】\n22. put on 穿上\n23. put off 推迟\n24. put up 张贴，举起\n25. put down 放下\n26. put away 收好，放好\n\n【take短语】\n27. take off 脱下，起飞\n28. take away 拿走\n29. take care of 照顾\n30. take part in 参加\n31. take place 发生\n32. take out 拿出\n\n【其他】\n33. give up 放弃\n34. give back 归还\n35. pick up 捡起\n36. think about 考虑\n37. agree with 同意\n38. wait for 等待' },
    { chapter: '下册 短语2', name: '短语2：be动词短语', formula: 'be good at, be interested in, be afraid of, be late for, be ready for', explanation: '【常见be动词短语】\n\n【be + 形容词 + 介词】\n1. be good at 擅长于\n2. be good for 对...有益\n3. be bad for 对...有害\n4. be interested in 对...感兴趣\n5. be afraid of 害怕\n6. be proud of 为...感到骄傲\n7. be full of 充满\n8. be busy with 忙于...\n9. be late for 迟到\n10. be ready for 为...准备好\n11. be different from 与...不同\n12. be the same as 和...一样\n13. be friendly to 对...友好\n14. be kind to 对...和蔼\n15. be strict with 对...严格\n16. be careful with 小心...\n17. be famous for 因...而著名\n18. be popular with 受...欢迎\n19. be angry with 对...生气\n20. be happy with 对...满意\n\n【be + 介词短语】\n21. be at home 在家\n22. be at school 在上学\n23. be at work 在工作\n24. be in hospital 住院\n25. be in bed 在床上，卧床\n26. be on duty 值日\n27. be on sale 出售\n28. be in danger 处于危险中\n29. be in trouble 处于困境中\n30. be on time 准时\n\n【be + 形容词 + 不定式】\n31. be able to 能够\n32. be glad to 很高兴...\n33. be sorry to 很抱歉...\n34. be sure to 一定会...\n35. be happy to 很高兴...' },
    { chapter: '下册 词性转换', name: '词性转换常见规律', formula: '名词加ful变形容词，形容词加ly变副词，动词加er变名词', explanation: '【常见词性转换规律】\n\n【名词 → 形容词】\n1. 名词 + ful（充满...的）\n   care → careful 小心的\n   help → helpful 有帮助的\n   use → useful 有用的\n   beauty → beautiful 美丽的\n\n2. 名词 + less（没有...的）\n   care → careless 粗心的\n   help → helpless 无助的\n   use → useless 无用的\n\n3. 名词 + y（多...的）\n   sun → sunny 晴朗的\n   rain → rainy 下雨的\n   cloud → cloudy 多云的\n   wind → windy 有风的\n   snow → snowy 下雪的\n   health → healthy 健康的\n\n4. 名词 + ous（...的）\n   danger → dangerous 危险的\n   fame → famous 著名的\n\n【形容词 → 副词】\n1. 形容词 + ly\n   quick → quickly 快地\n   slow → slowly 慢地\n   careful → carefully 仔细地\n   happy → happily 高兴地\n   easy → easily 容易地\n\n【动词 → 名词】\n1. 动词 + er / or（做...的人）\n   teach → teacher 老师\n   work → worker 工人\n   drive → driver 司机\n   visit → visitor 游客\n   act → actor 演员\n\n2. 动词 + ing / tion / ment（动作或结果）\n   swim → swimming 游泳\n   build → building 建筑物\n   decide → decision 决定\n   develop → development 发展\n\n【形容词 → 名词】\n1. 形容词 + ness\n   happy → happiness 幸福\n   ill → illness 疾病\n   kind → kindness 善良\n\n2. 形容词 + ty\n   safe → safety 安全\n   difficult → difficulty 困难' },
    { chapter: '下册 不规则动词', name: '不规则动词表', formula: 'AAA型、ABB型、ABC型', explanation: '【常见不规则动词分类表】\n\n【AAA型（原形、过去式、过去分词相同）】\ncost → cost → cost 花费\ncut → cut → cut 切，割\nput → put → put 放\nread → read → read 读\nlet → let → let 让\nhit → hit → hit 击打\nset → set → set 安置\nhurt → hurt → hurt 受伤\n\n【ABB型（过去式和过去分词相同）】\n1. 词尾加t：\n   learn → learnt → learnt 学习\n   mean → meant → meant 意思是\n   sleep → slept → slept 睡觉\n   keep → kept → kept 保持\n   feel → felt → felt 感觉\n   spell → spelt → spelt 拼写\n\n2. 改d为t：\n   build → built → built 建造\n   lend → lent → lent 借出\n   send → sent → sent 发送\n   spend → spent → spent 花费\n\n3. 变中间元音：\n   sit → sat → sat 坐\n   win → won → won 赢\n   shine → shone → shone 照耀\n   dig → dug → dug 挖\n   hang → hung → hung 悬挂\n\n4. 其他：\n   have → had → had 有\n   hear → heard → heard 听见\n   make → made → made 制作\n   pay → paid → paid 付款\n   say → said → said 说\n   sell → sold → sold 卖\n   tell → told → told 告诉\n   stand → stood → stood 站\n   understand → understood → understood 理解\n\n【ABC型（三者都不同）】\n1. ow → ew → own:\n   blow → blew → blown 吹\n   know → knew → known 知道\n   grow → grew → grown 生长\n   throw → threw → thrown 扔\n\n2. i → a → u:\n   begin → began → begun 开始\n   drink → drank → drunk 喝\n   ring → rang → rung 响\n   sing → sang → sung 唱\n   swim → swam → swum 游泳\n\n3. 其他常见：\n   go → went → gone 去\n   do → did → done 做\n   see → saw → seen 看见\n   eat → ate → eaten 吃\n   give → gave → given 给\n   take → took → taken 拿走\n   speak → spoke → spoken 说\n   write → wrote → written 写\n   get → got → got / gotten 得到\n   forget → forgot → forgotten 忘记\n   come → came → come 来\n   run → ran → run 跑\n   be → was/were → been 是' },
];

console.log('========== 任务2：生成一年级英语 ==========');

const upperList = saveKnowledge(g1EnglishUpper, 1, 'english', 'upper');
const lowerList = saveKnowledge(g1EnglishLower, 1, 'english', 'lower');
const vocabUpperList = saveKnowledge(g1EnglishVocabUpper, 1, 'english_vocab', 'upper');
const vocabLowerList = saveKnowledge(g1EnglishVocabLower, 1, 'english_vocab', 'lower');

console.log('\n生成英语知识点例题中...');
const upperExamples = generateExamples(upperList, 'g1', 'english', 'upper');
const lowerExamples = generateExamples(lowerList, 'g1', 'english', 'lower');

console.log(`\n英语上册知识点：${upperList.length}个，例题：${upperExamples.length}道`);
console.log(`英语下册知识点：${lowerList.length}个，例题：${lowerExamples.length}道`);
console.log(`英语词汇上册：${vocabUpperList.length}个`);
console.log(`英语词汇下册：${vocabLowerList.length}个`);
console.log(`英语例题总数：${upperExamples.length + lowerExamples.length}道`);
console.log('\n========== 任务2完成 ==========');
